### ISSUE TITLE
List all images, some ID's are non-existent

### ISSUE THREAD

**Issue by SVQTQ** [digitalocean/api-v2#100]
```
curl -X GET "https://api.digitalocean.com/v2/images/" -H "Authorization: Bearer $TOKEN" | grep --col debian
```

This gives me the debian 6.0 x32, x64 and 7.0 x32, x64 id's.. Whenever I try to use the 7.0 x64 image (id: 6372526) it gives me an error, stating that the specified image was not found.
However, when I use the x32 (6372528), my droplet is created. These 2 id's were fetched from the same link. the image-slug doesn't work either.

I'm trying to use salt-cloud to create droplets. This worked for me without a problem up until friday, 24th Oct.
Now I can only create debian 7.0 x32 droplets, whilst I kind of need the x64 image.
If any more info is required, let me know, I'l be willing to provide the info needed

**Comment by wwkeyboard** [comment]
This sounds like an issue with creating the image itself, which seems like something our support team would be happy to help with. Opening a support ticket will be fastest way to get help with this kind of issue. 
https://cloud.digitalocean.com/support
