### ISSUE TITLE
Tony Hoare's billion-dollar mistake

### ISSUE THREAD

**Issue by reynir** [digitalocean/api-v2#101]
I see that in some places there are types like `nullable number`, particularly in the dns record objects. Unfortunately, not all `nullable` types are marked as such. I noticed that the `region` field in an `action` object can be null, although the documentation says it's a string. It would be great if the types were more precise in that regard.

> I call it my billion-dollar mistake. It was the invention of the null reference in 1965. At that time, I was designing the first comprehensive type system for references in an object oriented language (ALGOL W). My goal was to ensure that all use of references should be absolutely safe, with checking performed automatically by the compiler. But I couldn't resist the temptation to put in a null reference, simply because it was so easy to implement. This has led to innumerable errors, vulnerabilities, and system crashes, which have probably caused a billion dollars of pain and damage in the last forty years.
- Tony Hoare, 2009

**Comment by phillbaker** [comment]
@reynir unfortunately nullable fields as a design consideration is locked into v2 of the API. We'll keep this in mind for future major versions, though.

We did find a couple cases of nullable objects in addition to the region field you mention. We'll get the docs updated. Thanks!
