### ISSUE TITLE
Size object no longer available on droplets

### ISSUE THREAD

**Issue by danpalmer** [digitalocean/api-v2#102]
From the documentation:

> Some of the attributes will have an object value. The region, image, and size objects will all contain the standard attributes of their associated types.

As of the breaking change in https://developers.digitalocean.com/changelog/api-v2/change-size-to-size-slug/ - this is no longer true.

Expected documentation:

> Some of the attributes will have an object value. The region, and image objects will all contain the standard attributes of their associated types.

**Comment by phillbaker** [comment]
Thanks, we'll get this clean up!

**Comment by phillbaker** [comment]
This has been fixed.
