### ISSUE TITLE
$droplet = $digitalocean->droplet(); issue

### ISSUE THREAD

**Issue by matif** [digitalocean/api-v2#105]
calling $droplet = $digitalocean->droplet(); returns this Exception Property "DigitalOceanV2\Entity\Image::minSize" should exist. and calling this $image = $digitalOcean->image(); returns Operation timed out after 5007 milliseconds with 0 bytes received.

Please help me to figure out these issues.

Thanks

**Comment by jeevatkm** [comment]
Might be this reason https://developers.digitalocean.com/changelog/api-v2/change-size-to-size-slug/

**Comment by matif** [comment]
No this is not the reason, I am trying with the PHP API but getting above error.

Thanks in advance.

**Comment by andrewsomething** [comment]
It looks like you're using toin0u's DigitalOceanV2 PHP wrapper. If so, you might want to open an issue on that repository. This repo is for tracking feedback about DigitalOcean's APIv2 not issues with individual third party libraries.

https://github.com/toin0u/DigitalOceanV2

**Comment by phillbaker** [comment]
Closing as per @andrewsomething's comment.
