### ISSUE TITLE
Fix feed of changelog page

### ISSUE THREAD

**Issue by Ajnasz** [digitalocean/api-v2#106]
On #105 I saw a link to https://developers.digitalocean.com/changelog/ page which is great!

However I found bugs with the atom/rss feeds.

The one, which is referred in the header of the page (https://developers.digitalocean.com/changelog/feed.xml) goes to 404.

I think it should be changed to the atom feed, which is linked in the sidebar.

Also the atom feed has an issue, because the articles are linked to digitalocean.com, so when I open it I get 404. Instead it should link to developers.digitalocean.com.

Thanks you very much!

**Comment by brookemckim** [comment]
@Ajnasz thanks for the report. We will get this fixed up!

**Comment by brookemckim** [comment]
@Ajnasz this is fixed, thanks again for the report.
