### ISSUE TITLE
no "next" page when listing /regions?per_page=x

### ISSUE THREAD

**Issue by chrisfarms** [digitalocean/api-v2#107]
If you set a low `per_page` value when fetching regions, then no pagination data is returned in the links section and the total incorrectly reports the total number of regions.

Effectively it looks like `per_page` is acting as `limit`

**Comment by daveworth** [comment]
Hello @chrisfarms - Thanks for the report.  We've rolled out an updated regions endpoint which should respect the standard pagination parameters correctly.  Thanks for the report!
