### ISSUE TITLE
Image Actions – Transfer to another user

### ISSUE THREAD

**Issue by ekytr** [digitalocean/api-v2#109]
Is it possible to use the API to transfer images to another user?

It is possible via the [web front-end](https://cloud.digitalocean.com/images), but I don't see any support in the API under [Image Actions](https://developers.digitalocean.com/v2/#transfer-an-image), as it only accepts a `region` option, and not an `email`.

![screen shot 2014-11-20 at 11 08 59 am](https://cloud.githubusercontent.com/assets/8039430/5131209/a7296f0a-70a5-11e4-8ecc-1d8c759a737b.png)

**Comment by brookemckim** [comment]
@ElijahKaytor we currently do not support this through the API. We do have it in our backlog and will post to the changelog when it is implemented.

**Comment by ekytr** [comment]
Sounds good, thanks.
