### ISSUE TITLE
Unable to filter only distributions/applications by the public and slug attributes in /images

### ISSUE THREAD

**Issue by bob-rove** [digitalocean/api-v2#11]
For example: Ghost 0.4.2 on Ubuntu 12.04 is not a distribution but it has a slug like all other distros.
I think you could follow agreement to not use slug attribute for anything other than distros.

Maybe it will be better if you split /images into /distributions, /applications and /snapshots (or /images), and add an image_id field, unique across all this endpoints. A little bit messy but it could simplify API usage.

**Comment by bobbytables** [comment]
@bob-rove Wanted to update you on this. We are tackling this and you'll see something soon. :smile:

**Comment by bob-rove** [comment]
Niiiice :)

**Comment by TomMalbran** [comment]
I am having the same issue. I would like to know if an image is a distribution or an application. Having a simple boolean attribute on the returned image data would be enough for me.

Before the latest change I was able to identify the application images by comparing the name with the distribution but right now it is no longer possible.

**Comment by bobbytables** [comment]
Hi @TomMalbran, right now we're currently working on the finishing touches of APIv2 and this feature will be rolled out soon.

**Comment by TomMalbran** [comment]
Great. Thanks!

**Comment by andrewsomething** [comment]
Note: We've added the ability to filter on on 'distros' and 'applications'

```
/v2/images?type=distribution
```

and

```
/v2/images?type=application
```

See: https://developers.digitalocean.com/changelog/api-v2/add-image-filtering/

**Comment by ghost** [comment]
@andrewsomething - Hi asb. Following up from DO community. Was the 'public' boolean filter also being planned for images?

**Comment by phillbaker** [comment]
@havelday any image that's in distribution or application filters is public. Is there something specific you're having trouble with?

**Comment by ghost** [comment]
@phillbaker => Just wanted one more filter to occur closer to where the data is maintained. In the particular case I'm dealing with, snapshots were created and the droplets were destroyed soon after. The app could not come up with the list of snapshots using the defunct droplet IDs, so it had to go through the entire list of images. A filter like

```
/v2/images?public=false
```

would make the query more efficient from an application point of view.

**Comment by phillbaker** [comment]
@havelday got it. We do have a `private=true` filter (https://developers.digitalocean.com/documentation/v2/#list-a-user-s-images), would that work?

**Comment by ghost** [comment]
@phillbaker => Yup, that will work. Thanks for including that filter.
