### ISSUE TITLE
Looks like Api-v2 use old records for DNS

### ISSUE THREAD

**Issue by sinelga** [digitalocean/api-v2#113]
About 20-30 days ago we are change ip addresses  of one ours servers it was used API v1
But now then we try get information by API v2 it's still old one.

curl -X GET -H 'Content-Type: application/json' -H 'Authorization: Bearer **' "https://api.digitalocean.com/v2/domains/k18.me" give as ip IN A 104.131.42.229
But it was changed many days ago

dig   k18.me   

k18.me.                 1799    IN      A       104.131.181.98 !!!

The same ip address on web console and it's correct so looks like 
V2 use old DB records at least for DNS records.

Thanks.

**Comment by bobbytables** [comment]
@sinelga  - I've looked into the issue for your records and have applied a potential fix. In the future the best avenue for help is by contacting our support team here at DigitalOcean.
