### ISSUE TITLE
Droplet JSON representation inconsistent

### ISSUE THREAD

**Issue by andrewstuart** [digitalocean/api-v2#114]
I'm working on a little Go wrapper and CLI for the digitalocean API and I just noticed that the Droplet representation has region as a string (slug) for droplet creation, but comes back as an object when querying all droplets.

I think it used to return a slug when querying, though I may be mistaken. Is there any chance that the response can always be a string, for a consistent representation? 

I think it's cleaner having just an identifier there and then I can look it up via the /regions endpoint if I need to know more info.

Also, thanks for an awesome product! :-)

**Comment by phillbaker** [comment]
@andrewstuart this is partly a design choice: at create time the user is choosing what region to put the droplet in (the object isn't appropriate here), but at query time we provide the entire object to reduce redundant calls to the API. You're right that we could force folks to do the additional call to the `/regions` endpoint, but we lean toward providing nested objects in the initial call where possible.

Please re-open this issue if you have any questions!
