### ISSUE TITLE
Resize action returning 422

### ISSUE THREAD

**Issue by gabriel403** [digitalocean/api-v2#117]
When sending a POST of
`{type:"resize",size:"8gb"}` to `https://api.digitalocean.com/v2/droplets/{{droplet.id}}/actions` for a droplet based in `lon1` I'm getting 422 and a message of `Size is too large to fit on your droplet's server`

When doing a GET to `https://api.digitalocean.com/v2/sizes` `lon1` is listed as an available region for that size

**Comment by brookemckim** [comment]
@gabriel403 the problem is not that the size is not available in that region, but that it is not available on the hardware your Droplet is on. We are actively working on fixing this as we understand it is a frustrating customer experience.

**Comment by gabriel403** [comment]
@brookemckim thanks for the reply, is it just memory that this applies to or drive space too? Or is that done as some kind of enterprise scale NAS?

**Comment by brookemckim** [comment]
This is memory.

**Comment by gabriel403** [comment]
@brookemckim sorry, what I meant was does drive space suffer from the same limitation, per physical server, or is drive space a giant pool of space?

**Comment by brookemckim** [comment]
Ah I see. Yes disk space has the same restrictions.
