### ISSUE TITLE
RateLimit, is it per authentication or per IP?

### ISSUE THREAD

**Issue by gabriel403** [digitalocean/api-v2#118]
I host a web app that integrates with the DO API, it requires the user to use a personal access token to access the DO API, I'm curious whether the RateLimit would be per access token or per IP? 

If 13 people do 100 requests in 1 hour for example that would put it over the rate limit by IP, but not by access token.

**Comment by brookemckim** [comment]
It is a per token ratelimit.

**Comment by gabriel403** [comment]
@brookemckim yay \o/
