### ISSUE TITLE
Graphs for Bandwidth, Disk and CPU

### ISSUE THREAD

**Issue by Yorkie595** [digitalocean/api-v2#12]
It would be pretty awesome if we were able to get droplet graph data from the API.

We could do something like request a specific time period and graph (out of CPU, Disk & Bandwidth), which could then be returned in the form of a Google Chart (https://developers.google.com/chart/) or in some other way.

It would be really helpful for me if you could do this.

Thanks!

**Comment by bob-rove** [comment]
+1

**Comment by jasonfill** [comment]
+1 I was just about to add this one as well. Would add a lot of value for us..

**Comment by AustinDizzy** [comment]
+1 I was just about to add this as well! This is initially why I was interested in the V2 API.

**Comment by ericof** [comment]
+1

**Comment by deivuh** [comment]
+1 this would be a nice feature for our applications.

**Comment by madsobel** [comment]
+1 Just send the numbers within the response. Limiting the use only to Google Charts would be terrible. There are so many chart libraries out there that are so much better.

**Comment by bob-rove** [comment]
I suppose that returning the data for specific time period could be difficult in terms of storing and retrieving such data, but it will be definitely awesome to get just the data, used to draw the existing charts in DO console.

**Comment by Yorkie595** [comment]
@madsobel - Google Charts was just a suggestion, great for simplicity but doesn't allow for much in the way of data customisation. Perhaps DO could make it so that the request can contain another parameter that would allow us to choose from the API returning the raw data (numbers) or 'premake' the graph in Google Charts or another client library depending on our needs.

**Comment by brookemckim** [comment]
This is planned, but we have do not have a launch date quite yet.
Thanks for the suggestion!

**Comment by Yorkie595** [comment]
@brookemckim That's great news! Thanks a lot.

**Comment by madsobel** [comment]
Regardless of how the end format will be. I really look forward to it, thanks a lot @brookemckim

**Comment by deivuh** [comment]
That's great! Thanks @brookemckim

**Comment by mickhansen** [comment]
+1

**Comment by toin0u** [comment]
Wow that will be very nice ! :)

**Comment by index0h** [comment]
+1

**Comment by ForbiddenEra** [comment]
+1 but this can easily be done with a script on your droplet, although native support would be nice.

**Comment by ForbiddenEra** [comment]
I'd rather JSON output though so I can use them with whatever graph system

**Comment by cybermania** [comment]
+1 for CPU/Disk/Network usage. I was looking at this primary.

**Comment by brookemckim** [comment]
Adding stats is planned, but no release date as of yet.
