### ISSUE TITLE
Associating Token Name/Identifier with Action

### ISSUE THREAD

**Issue by ghost** [digitalocean/api-v2#120]
Here's the scenario: I have two tokens named **Master** and **Minion**. Each tokens is associated with only one computer, and each token has read/write attributes. The **Minion** token is used more often to initiate account actions, but once in a while the **Master** token is used.  How would you track which token was used in an account action, let's say for auditing reasons?

In the current schema for _actions_, there doesn't seem to be any way to relate the token identifier with the action. Or did I miss a relationship somewhere else?

**Comment by phillbaker** [comment]
@havelday good question. Currently we don't expose information for auditing purposes through the API. You _can_ see actions taken on your resources via the control panel at https://cloud.digitalocean.com/settings/security. While we don't differentiate between individual tokens right now, that's something we could plan for a future release.

For some more context, what sort of audit are you preparing for?

**Comment by ghost** [comment]
@phillbaker - A review could potentially be initiated if any billing or security questions arise. The thinking is that a company may have one DO account, for example, that have a few groups accessing that account to spin up VPSs on demand. Security tokens can then be used to identify account activities on a per group basis. Of course having seperate accounts is a solution, but some companies may prefer to track one bill for cloud computing usage.

**Comment by ghost** [comment]
The newly introduced Team concept seems to cover this, although a clean API for it would be nice. Closing.
