### ISSUE TITLE
Private images have duplicate regions

### ISSUE THREAD

**Issue by fichek** [digitalocean/api-v2#122]
[User's images](https://developers.digitalocean.com/v2/#list-a-user-s-images) seems to always have a duplicate region from which it originated in its `regions` array.

For example a snapshot of my droplet from NYC2 has these regions: `sfo1, nyc2, ams2, nyc2` while a snapshot of a newly created droplet in AMS3 has these: `ams3, ams3`.

While it seems like a bug, it does have a nice side-effect of being able to tell where the droplet was created, but I'd rather have that available as a separate key (not that I can think of any use case where that would be required and you can look up individual droplets' snapshots anyway).

**Comment by phillbaker** [comment]
This has been fixed, thanks.
