### ISSUE TITLE
account always returns email_verified: false

### ISSUE THREAD

**Issue by fichek** [digitalocean/api-v2#123]
As the title says.

**Comment by fichek** [comment]
Just confirmed with a new account that even has this confirmation in the control panel:

![email verified](http://i.imgur.com/ZhLGZwV.png)

/v2/account returns `email_verified: false`

**Comment by phillbaker** [comment]
Thanks @fichek we'll take a look.

**Comment by phillbaker** [comment]
Hi @fichek, we're not able to reproduce this. As the the [documentation](), this value is a boolean. What response to you receive when you try this via curl? For example, `curl -X GET -H 'Content-Type: application/json' -H "Authorization: Bearer $TOKEN" "https://api.digitalocean.com/v2/account"`?

**Comment by fichek** [comment]
My apologies for the confusion caused. I'm using Apple's JSON parser which converts booleans into numbers. The response indeed contains `email_verified: false`, not `email_verified: 0`. But yeah it still returns `false` (`0`) for both accounts when I'm expecting it to return `true` (`1`).

**Comment by phillbaker** [comment]
Ah - yes, it looks like this is wrong in some cases. We'll get this fixed up.

**Comment by phillbaker** [comment]
@fichek we've deployed a fix. Thanks for your patience and help!
