### ISSUE TITLE
min_size is missing in the documentation

### ISSUE THREAD

**Issue by toin0u** [digitalocean/api-v2#125]
> The Image JSON object now includes a min_size attribute that contains the slug of the minimum size droplet required for that image. For example a snapshot of a 1 Gig droplet will have “1gb” as it’s min_size.

Source: https://developers.digitalocean.com/documentation/changelog/api-v2/change-size-to-size-slug/

**Comment by phillbaker** [comment]
Sorry, the changelog is wrong, it's `min_disk_size`: https://developers.digitalocean.com/documentation/v2/#images. We'll update the changelog.

**Comment by toin0u** [comment]
Thanks! :)
