### ISSUE TITLE
Differentiate backups from snapshots

### ISSUE THREAD

**Issue by fichek** [digitalocean/api-v2#126]
Right now, snapshots and backups appear identical in the api. We can get them separately for each droplet which is nice, but here's my use case:

I'm listing [all of user's images](https://developers.digitalocean.com/documentation/v2/#list-a-user-s-images) and then for each image providing a region availability table that shows where the image is available and lets the user transfer it to regions where it is not.
![screen shot](https://cloud.githubusercontent.com/assets/956646/6530179/f79501de-c42e-11e4-8f15-b15315459eb1.png)

Now of course, if the user selects an image that is a backup instead of a snapshot, I have no way to tell that difference and the user can try to transfer that image to selected region which gives the following error:

```
{"id":"unprocessable_entity","message":"Backups can not be transfered to other regions"}
```

I could query each droplet's snapshots separately, but it's hacky and may waste a lot of api requests for users with a lot of droplets. Is there any way you could add something to just differentiate the private image types? I'd suggest a `type` string key that could be `public`, `snapshot` or `backup` to replace the current `public` boolean key but that's a pretty breaking change so I'd take anything that fixes this problem.

**Comment by fichek** [comment]
It would also be nice to differentiate temporary from permanent snapshots. Btw, I'm not sure if this is intended or not, but you can transfer temporary snapshots to different regions via API. You can't do it via control panel, so I have a feeling it might be a bug.

**Comment by phillbaker** [comment]
@fichek we'll get this scheduled and update this issue.

**Comment by phillbaker** [comment]
@fichek we've deployed this change, please see: https://developers.digitalocean.com/documentation/changelog/api-v2/add-type-to-images/.

**Comment by fichek** [comment]
@phillbaker awesome, thank you!
