### ISSUE TITLE
Server Grouping/Tagging

### ISSUE THREAD

**Issue by jasonfill** [digitalocean/api-v2#13]
This might not fall under the API as much as a feature in general - we would use it via the API so I will add it.  It would be helpful if there was a way to tag or group servers - this would provide a flexible way to snag specific droplets and take a specific action on them.  Additionally, combined with issue #12 would allow for some more flexible dash-boarding and data retrieval.

**Comment by progrium** [comment]
+1

**Comment by kontrafiktion** [comment]
+1

would simplify dynamic provisioning (configuring new 'compute nodes' based on a tag) when using Ansible etc.

**Comment by brookemckim** [comment]
This is a very good idea, but more of a general product feature request. Posting over on http://digitalocean.uservoice.com/ is the best way to make production suggestions.

**Comment by jasonfill** [comment]
@brookemckim sorry about that, I was not aware of the uservoice setup.  Looks like this is basically accounted for (entered in 2012) as a suggestion http://digitalocean.uservoice.com/forums/136585-digitalocean/suggestions/2712160-group-servers
