### ISSUE TITLE
Curl example for adding a name server?

### ISSUE THREAD

**Issue by opn** [digitalocean/api-v2#130]
When I post the following JSON:

```
{"type":"NS","data":"ns1.digitalocean.com","name":null,"priority":null,"port":null,"weight":null}
```

 to the `/v2/domains/$DOMAIN_NAME/records` endpoint - I get the following error response:

```
error 422 Unprocessable Entity
```

I can create A records following the curl example in the docs. It's not clear what the "name" record should be - the docs say it is not required. I've tried "@" - no joy. 

Can someone give me a curl example?

**Comment by andrewsomething** [comment]
How are you making the call? It seems like you are loosing the message field of the error response. Using curl directly, you can see the issue quite clearly:

```
$ curl -X POST -H 'Content-Type: application/json' -H \
>   'Authorization: Bearer '$DO_TOKEN'' \
>    -d '{"type":"NS","data":"ns1.digitalocean.com","name":null,"priority":null,"port":null,"weight":null}' \
>    "https://api.digitalocean.com/v2/domains/another-example.com/records"
{"id":"unprocessable_entity","message":"Data needs to end with a dot (.)"}
```

A correctly formatted request would look like:

```
$ curl -X POST -H 'Content-Type: application/json' -H 'Authorization: Bearer '$DO_TOKEN'' \
>    -d '{"type":"NS","data":"ns1.digitalocean.com."}' \
>    "https://api.digitalocean.com/v2/domains/another-example.com/records"
{"domain_record":{"id":6110483,"type":"NS","name":"@","data":"ns1.digitalocean.com","priority":null,"port":null,"weight":null}}
```

**Comment by opn** [comment]
Thanks - that did it :)

**Comment by macb** [comment]
@andrewsomething to the rescue! :tada:
