### ISSUE TITLE
Check Scopes

### ISSUE THREAD

**Issue by heyvito** [digitalocean/api-v2#133]
Hi guys! I just talked with DO support moments ago, and we concluded this would be a nice feature:
There is currently no way to check an existent token scopes. GitHub has already implemented something like that (https://developer.github.com/v3/oauth/#scopes), and this would allow users to authenticate in an app just by using one of their personal tokens.

Suggestions?

**Comment by phillbaker** [comment]
@victorgama thanks for opening the issue, we definitely want to move toward this, but as of yet, we don't have a timeline. We'll update this issue with more information as we have it.

**Comment by heyvito** [comment]
Oh, I see. No problem, will wait until you guys sort this out. :four_leaf_clover:

**Comment by feltrite** [comment]
@victorgama @phillbaker  By the way, still waiting for that Scope check URI 👎 
I believe its the only thing the API lacks, 3 Years!

@digitaloceanbot

**Comment by andrewsomething** [comment]
Custom scopes for DigitalOcean personal access tokens (PATs) reached generally available April 17th 2024:

**Release Note:** https://docs.digitalocean.com/release-notes/api/#2024-04-17
**Feature Request:** https://ideas.digitalocean.com/interfaces/p/scoped-api-access

**Documentation:**

https://docs.digitalocean.com/reference/api/create-personal-access-token/
https://docs.digitalocean.com/reference/api/api-reference/#section/Authentication
