### ISSUE TITLE
Accept Attribute To Shutdown Instance When Creating Snapshot

### ISSUE THREAD

**Issue by brandongalbraith** [digitalocean/api-v2#134]
Currently, you need to issue a shutdown or power off request for an instance, verify the instance is stopped, and then issue a [snapshot](https://developers.digitalocean.com/documentation/v2/#snapshot-a-droplet) request.

Ideally, the snapshot request would accept the attribute `shutdown` (which would be a boolean), and gracefully shutdown the instance before attempting to snapshot the instance.

Request Body Example:

```
{
  "type": "snapshot",
  "shutdown": true,
  "name": "Nifty New Snapshot"
}
```

**Comment by mikeknoop** [comment]
As the API currently works, it's unknowable how long a droplet takes to shutdown when you have to call `shutdown` and `snapshot` serially. You have to write code to continually check. The proposal above makes it much cleaner for devs to take snapshots -- a very popular thing to do with the API.

**Comment by bryanhelmig** [comment]
:+1:

**Comment by gregelizondo** [comment]
:+1: This would be nifty

**Comment by brookemckim** [comment]
This is an interesting idea. One part to consider is we always recommend powering down from within the Droplet to prevent filesystem corruption. I would be a bit uncomfortable documenting a method which side-stepped this.

**Comment by brandongalbraith** [comment]
My assumption was this parameter would use the same logic as used by https://developers.digitalocean.com/documentation/v2/#shutdown-a-droplet; initiating a graceful shutdown of the droplet, allowing any running processes to safely exit and leaving the filesystem in a consistent state.

**Comment by brookemckim** [comment]
We do issue a graceful shutdown, but it does not work in all cases. Since we do not run any agent on the Droplet we have to rely on KVM behaving correctly to perform the graceful shutdown.

**Comment by brandongalbraith** [comment]
Would it be possible to accept a `force` bool attribute? If not specified or set to false, attempt the droplet shutdown before the snapshot, and if the droplet is unable to gracefully shutdown, the snapshot would fail. If set to true, attempt a graceful shutdown (allowing a reasonable amount of time for the instance to shutdown, say between 60-120 seconds), and then terminate the droplet (forced power off) if the graceful shutdown is unsuccessful.

```
{
  "type": "snapshot",
  "shutdown": true,
  "force": true,
  "name": "Nifty New Snapshot"
}
```

**Comment by brandongalbraith** [comment]
@brookemckim Any update on this?
