### ISSUE TITLE
add image slugs

### ISSUE THREAD

**Issue by blunckr** [digitalocean/api-v2#137]
It would be nice to be able to set the slug when creating a snapshot so I could use that later to pull the image. https://github.com/digitalocean/api-v2/issues/98 (snapshot create should return ids) would also solve the problem for me. Currently after creating an snapshot I have to keep pulling all the images down and looking for the one I created by name to store the id. But if I had a slug (or id), I could just use the path for that single image until it appears.

**Comment by phillbaker** [comment]
@blunckr thanks for clarifying the problem - currently image slugs are only for public images, but we'll get #98 back on the list of things to look at. For now I think we can close this issue as duplicate?
