### ISSUE TITLE
CSS seems broken on Authorize Application page

### ISSUE THREAD

**Issue by trvbr** [digitalocean/api-v2#138]
It looks like some CSS for this page got dropped accidentally, maybe during the last site-wide redesign?

<img width="403" alt="screen shot 2015-08-26 at 9 20 58 pm" src="https://cloud.githubusercontent.com/assets/6646266/9512556/c0eee7d4-4c38-11e5-8bad-746b528c74bc.png">

**Comment by trvbr** [comment]
Yee-uhh!! Looks good now. Thank you guys.

**Comment by phillbaker** [comment]
Thanks @trvbr.
