### ISSUE TITLE
Very minor suggestion for API documentation

### ISSUE THREAD

**Issue by granthbr** [digitalocean/api-v2#139]
Using the curl commands from a Mac or, possibly, from BSD the curl command needs to be surrounded by double quotes not single. I don't know exactly how you would note that but it would be a nice suggestion to make for Mac users. 
Thanks,
Brandon

**Comment by phillbaker** [comment]
Thanks @granthbr, are you using a substitution like `$TOKEN` in the single quotes?

**Comment by phillbaker** [comment]
This was changed.
