### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by jasonfill** [digitalocean/api-v2#14]
Many people just group webhooks in with API, so I will add it here.  The addition of webhooks to report the various server events would be particularly helpful.  If the implementation also had a trigger on some of the stats that are reported on #12 it would us to create some interesting scaling solutions.

**Comment by progrium** [comment]
I'm all for webhooks. There's no official roadmap, but we've talked about this a lot already and we all seem to want it.

**Comment by kjs3** [comment]
Yes please.

**Comment by ForbiddenEra** [comment]
+1

**Comment by toin0u** [comment]
+1

**Comment by brookemckim** [comment]
These are planned, but we do not have a release date quiet yet.

**Comment by ryanwinchester** [comment]
Any word? Still see don't see these.

**Comment by zxfrank** [comment]
Having an optional "webhook" url when initiating a droplet would be more than usefull and we wouldn't have to call for the action status until completed.

**Comment by subomi** [comment]
We launched [Nohooks](https://nohooks.io) and added support for DigitalOcean Droplet events. 🎉

**Comment by zxfrank** [comment]
So basically, the polling is offloaded to a 3rd party.... adding configuration and complexity.

**Comment by subomi** [comment]
Yes, and it works. You should try it out. 

We hacked this together in less than a week. Ideally, we would love to open-source the code so we can collectively improve the polling system and event types/payload, pending we get native support from these platforms. But I'll need to do some code cleanup first.

**Comment by ForbiddenEra** [comment]
> We hacked this together in less than a week.

It took less than a week to hack together but just under 9 years to implement?

Note that I wouldn't make a comment like this for a standard open source project where everything is free; but as a paying DO customer this is something I needed 9 years ago!

Not trying to be disrespectful or rude but it's not a good look for a business when you say something took little effort yet that little effort took 9 years!

I always thought DO was great. I would've honestly thought that DO architecture would've changed so much over this time that a better solution would exist and/or that this no longer apply. I can't really comment as I only use DO in a minor personal capacity now.

**Comment by subomi** [comment]
Ah, @ForbiddenEra, I think you misread my comment. Nohooks is unaffiliated with DO. Our primary project is [Convoy](https://github.com/frain-dev/convoy), a service that allows you to add webhooks to your API in minutes. We only built Nohooks to show what is possible and provide users with what they truly need.

**Comment by ForbiddenEra** [comment]
> Ah, @ForbiddenEra, I think you misread my comment. Nohooks is unaffiliated with DO. Our primary project is [Convoy](https://github.com/frain-dev/convoy), a service that allows you to add webhooks to your API in minutes. We only built Nohooks to show what is possible and provide users with what they truly need.

Apologies; not so much that I misread it, just more that I didn't fully realize you were a third party - in that case, good on you for trying to provide a solution..!

and still meh for DO not, though as I said nearly 10 years later I'm not even sure what I was trying to do back then or if it would apply with their architecture changes :)
