### ISSUE TITLE
Consistent API response structure for /v2/droplet_upgrades

### ISSUE THREAD

**Issue by jeevatkm** [digitalocean/api-v2#140]
Currently this API responds like -

``` json
[
  {
    "droplet_id": 123,
    "date_of_migration": "2014-12-01T12:00:00Z",
    "url": "https://api.digitalocean.com/v2/droplets/123"
  }
]
```

**which is different structure then from rest of the V2 APIs**. Kindly make it consistent like below:

``` json
{
  "upgrades": [
    {
      "droplet_id": 123,
      "date_of_migration": "2014-12-01T12:00:00Z",
      "url": "https://api.digitalocean.com/v2/droplets/123"
    },
    {
      "droplet_id": 456,
      "date_of_migration": "2014-12-01T12:00:00Z",
      "url": "https://api.digitalocean.com/v2/droplets/456"
    }
  ]
}
```

**Comment by GrahamCampbell** [comment]
Is it not too late now?

**Comment by jeevatkm** [comment]
No, I believe this API added after v2 final release (out-of-beta). I'm maintaining [java client for DO REST APIs](https://github.com/jeevatkm/digitalocean-api-java). While incorporating droplet_upgrades api, I noticed the difference in response structure. So I'm notifying DO to take care.

**Comment by GrahamCampbell** [comment]
Wait, so are you saying digital ocean broke their API after they said it was stable, or are you saying that you think they should break it to make it more consistent?

**Comment by jeevatkm** [comment]
No, I'm not saying they broke it. 

What I'm trying to say is; DO introduced new API (/droplet_upgrades) which provides details of currently scheduled droplets for upgrades. This API response structure is different from others.

**Comment by GrahamCampbell** [comment]
So, you're suggesting they break it then. That's why I said it's probably too late to correct this error. A possible solution might be to add a new endpoint though?

**Comment by jeevatkm** [comment]
Oh I see, Thanks, Will wait for DO response on this.

**Comment by phillbaker** [comment]
Hi @jeevatkm thanks for pointing this out. The endpoint wasn't consistent. 

However, the quick answer on this is that it doesn't really matter - the upgrades that this endpoint refers to have been completed, and this endpoint will return an empty array for the forseeable future. If we have the need to do more droplet upgrades, we'll revisit the structure and make a decision then. Does that help?

**Comment by jeevatkm** [comment]
Thanks.
