### ISSUE TITLE
Invalid redirect URI

### ISSUE THREAD

**Issue by beecrowd** [digitalocean/api-v2#143]
Hi!

I am integrating HydridAuth to my app and I decided to use the DigitalOcean integration. However, even though the callback URL registered in the app in the same as the one in DO settings, I keep getting "The redirect uri included is not valid.".

This is the callback URL I have registered in the DO API:
`**my-domain.com**/hybrid-auth/endpoint?hauth.done=DigitalOcean`

Once I click on login in my website I redirect the user to:
`https://cloud.digitalocean.com/v1/oauth/authorize?client_id=**my-client-id**&redirect_uri=https%3A%2F%2F**my-domain.com**%2Fhybrid-auth%2Fendpoint%3Fhauth.done%3DDigitalOcean&response_type=code&state=**state-code**&scope=read+write`

If you check the redirect_uri parameter and decode it, you get:
`https://**my-domain.com**/hybrid-auth/endpoint?hauth.done=DigitalOcean`

Which is the same URL as the one registered in the DO API. However, the screen gives me:

An error has occurred
The redirect uri included is not valid.

Screenshot:
(https://www.dropbox.com/s/pd2mwjd2zlj8ps7/Screenshot%20from%202016-04-04%2017%3A54%3A17.png?dl=0)

I not sure what is wrong in this case, since the URL is the same. I suggest you to also include the parsed URL in the error page as Google does. This one it is easier to troubleshoot the problem.

Any ideas of what may be causing this?

**Comment by Vanuan** [comment]
Having the same problem with Docker Cloud

Redirect URL is the following:

https://cloud.docker.com/api/tutum/v1/credentials/oauth/digitalocean/complete/

**Comment by mchitten** [comment]
Hi @urionlinejudge, it seems to be complaining because you've included the query string in your callback url on your application. In this case all you really need is the domain + path, and you can include arbitrary query string params in the `redirect_uri`.

So basically, in this case, you can set your callback url (on your application) to:

```
**my-domain.com**/hybrid-auth/endpoint
```

Then when you're redirecting back to us, you can specify your query string:

```
https://cloud.digitalocean.com/v1/oauth/authorize?client_id=**my-client-id**&redirect_uri=https%3A%2F%2F**my-domain.com**%2Fhybrid-auth%2Fendpoint%3Fhauth.done%3DDigitalOcean&response_type=code&state=**state-code**&scope=read+write
```

Then we should redirect the user back to:

```
https://**my-domain.com**/hybrid-auth/endpoint?hauth.done=DigitalOcean&code=abc
```

**Comment by andrewsomething** [comment]
@Vanuan The issue with Docker Cloud was on their end. We reached out to them earlier and it should now be resolved.

**Comment by Vanuan** [comment]
@andrewsomething Thanks a lot! You rock!

**Comment by andrewsomething** [comment]
No problem!

I'm going to go ahead and close this. @urionlinejudge please reopen if @mchitten's response didn't resolve your issue.
