### ISSUE TITLE
Seems like snapshot API is very limited now

### ISSUE THREAD

**Issue by route** [digitalocean/api-v2#144]
You can only create a snapshot for a droplet and cannot destroy, move between regions, change owner etc..

PS: Why does droplet go active after creating a snapshot if I manually turned it off before it?

**Comment by andrewsomething** [comment]
Hi!

If you take a look at the docs for the `/v2/images` endpoint, you can do most of what you are looking for:
- Destroy a snapshot: https://developers.digitalocean.com/documentation/v2/#delete-an-image
- Transfer to a different region: https://developers.digitalocean.com/documentation/v2/#transfer-an-image

Though the API does not currently support changing the owner of a snapshot.

**Comment by route** [comment]
Oh that was confusing, thank you! Then just one point left for clarifying - PS.
