### ISSUE TITLE
Billing API

### ISSUE THREAD

**Issue by vezaynk** [digitalocean/api-v2#145]
I lurked around the docs and couldn't find any interface that would allow me check my balance. It would be very nice if I could see my account balance on my own webpages/widgets.

**Comment by MaXFalstein** [comment]
We would be able to add push notifications for our DO balances with this addition to the API.

**Comment by bessarabov** [comment]
Several links on this topic:
- suggestion that billing shoud be implemented in api https://digitalocean.uservoice.com/forums/136585-digitalocean/suggestions/4012060-provide-billing-details-in-the-api
- https://github.com/digitalocean/api-v2/issues/4
- https://github.com/digitalocean/api-v2/issues/38
- https://github.com/digitalocean/api-v2/issues/61
- https://github.com/digitalocean/api-v2/issues/124

**Comment by zssarkany** [comment]
This feature would be really useful.
Is there any new info about it?

**Comment by wiktor-k** [comment]
Nothing significant changed in the API but at least now DO is sending direct links to invoices in payment notification emails.

**Comment by arekkusu** [comment]
This should really be implemented

**Comment by DaHaiz** [comment]
+1

**Comment by ale26** [comment]
+1

**Comment by mkarnicki** [comment]
Could we please not start a +1 thread? There's a github feature for this and 28 people so far have properly made use of it. Folks are subscribed to get material updates on this issue, not +1's. Thank you for your understanding.

**Comment by mauricio** [comment]
Hey folks, best place to bring this up is at https://digitalocean.uservoice.com/forums/136585-digitalocean not here.

**Comment by ale26** [comment]
https://digitalocean.uservoice.com/forums/136585-digitalocean/suggestions/4012060-provide-billing-details-in-the-api

**Comment by billybraga** [comment]
Any update ? The links to uservoice return a 404 error.

**Comment by andrewsomething** [comment]
I'm happy to share that there has been some movement on this. Balance information is now available via the API. See the API changelog for more details: 

https://developers.digitalocean.com/documentation/changelog/api-v2/new-endpoint-for-retrieving-balance-information/

Stay tuned for more update.
