### ISSUE TITLE
Clarify the expected format of `user_data` API options

### ISSUE THREAD

**Issue by rgrannell1** [digitalocean/api-v2#147]
I've recently started using the (v2) APIs, and I've found it easy to use, clearly-documented and extremely fast. I've found the [documentation](https://developers.digitalocean.com/documentation/v2/) for cloud-init support lacking, and I hope you can describe its expected formats in more detail in future.

The API documentation mentions that a `user_data` parameter can be set, but doesn't mention cloud-init (which will be a common reason for setting this option) doesn't explain how this can be used for cloud-init based installations.

I assumed DigitalOcean would support base64-encoded gzipped cloud-init scripts. This didn't seem to be supported, so I'd like to know:
- which user-data encodings (for cloud-init scripts) are supported? Plain-text only, or base-64 encoded?
- can the data be gzipped?
- what is the maximum supported byte-count for a cloud-init script?

**Comment by shivjm** [comment]
I just ran into the same issue. It was very confusing to pass a Bash script as user data via Terraform with a MIME type of `text/x-shellscript` and using gzip + Base64 only to find the Base64 form itself with a `text/x-not-multipart` MIME type in the Droplet and the requisite warning in the cloud-init logs:
```
Unhandled non-multipart (text/x-not-multipart) userdata: [redacted]
```
(I hope the extra information makes this issue easier to find for others.)

**Comment by zypA13510** [comment]
Seems to be fixed now. From [DigitalOcean API Reference > Droplets > Create a New Droplet](https://docs.digitalocean.com/reference/api/api-reference/#operation/droplets_create):

> **user_data** | string
> A string containing 'user data' which may be used to configure the Droplet on first boot, often a 'cloud-config' file or Bash script. It must be plain text and may not exceed 64 KiB in size.

**Comment by rgrannell1** [comment]
Thanks, closing!
