### ISSUE TITLE
Disabling/enabling backups via API

### ISSUE THREAD

**Issue by bob-rove** [digitalocean/api-v2#15]
This ability only present in DO console so I think it will be nice to take this action via API.
In case of enabling backups via API - is there any architecture constraint preventing from making it available via API?

**Comment by macb** [comment]
Backups can already be enabled via the API at droplet create with the `backups` field. However, disabling them after create is definitely something we can support to stay consistent with the console.

**Comment by macb** [comment]
@bob-rove just deployed a change to bring the api to be consistent with console in this regard. It is now possible to issue a `disable_backups` `Droplet Action` which will take care of that. Thanks again!

**Comment by bob-rove** [comment]
Thanks!
