### ISSUE TITLE
Typo: "attach" instead of "detach" 

### ISSUE THREAD

**Issue by shubhamoli** [digitalocean/api-v2#150]
Inside API v2 Docs, **BlockStorage Actions section** -> **Remove a volume from a droplet by Name**, it is _set the "type" attribute to **attach**_ , IMHO, it must be **_detach_**.

**Comment by andrewsomething** [comment]
It seems we overlooked closing out this issue when we deployed the fix. 

https://developers.digitalocean.com/documentation/v2/#remove-a-block-storage-volume-from-a-droplet-by-name

Thanks for catching this!
