### ISSUE TITLE
:id must be $DROPLET_ID

### ISSUE THREAD

**Issue by shubhamoli** [digitalocean/api-v2#151]
In all of the D.O APIv2 docs, the convention to indicate variable endpoints is $VAR_NAME, but inside 
**droplets** >> **list neighbors of a droplet** , it is _GET request to /v2/droplets/**:id**/neighbors_ which I think must be _GET request to /v2/droplets/**$DROPLET_ID**/neighbors_

**Comment by andrewsomething** [comment]
Looks like this was fixed sometime ago, but we neglected to close the issue:

https://developers.digitalocean.com/documentation/v2/#list-neighbors-for-a-droplet

**Comment by shubhamoli** [comment]
Thanks for fixing it
