### ISSUE TITLE
$DRIVE_ID or $VOLUME_ID

### ISSUE THREAD

**Issue by levidurfee** [digitalocean/api-v2#153]
When referring to Block Storage in the docs, it sometimes refers the unique identifier for the Block Storage volume as `$DRIVE_ID` and `$VOLUME_ID`, I assume they're interchangeable.

Would it be better to use one variable to reduce any possible confusion?

**Comment by phillbaker** [comment]
Thanks, we'll get this fixed up.

**Comment by andrewsomething** [comment]
Just wanted to provide a quick update: We deployed a fix for this awhile back and forgot to close out this issue.

Thanks again for catching this!
