### ISSUE TITLE
Digital Ocean have updated the API

### ISSUE THREAD

**Issue by FreshSites** [digitalocean/api-v2#154]
creating droplets has now been reordered in the API and extra fields added for monitoring.

this has broken our integration completely stopping any droplets from being created.

The new order is here: https://developers.digitalocean.com/documentation/v2/#create-a-new-droplet

**Comment by brookemckim** [comment]
Hello FreshSites,

Reordering of keys within a JSON object nor adding new keys to the object are breaking changes. We recommend that you do not rely on specific order of keys within an Object and instead the key itself.

What program language are you using? There may be a maintained client available that you can plug-in so you do not have to worry about these kinds of changes.
