### ISSUE TITLE
Enabling/disabling private networking just as public ipv6

### ISSUE THREAD

**Issue by bob-rove** [digitalocean/api-v2#16]
Will be great to be able to enable or disable ipv4 private networking the same way as public ipv6.

**Comment by brookemckim** [comment]
We will add the ability to enable private networking. You will still have to login to the Droplet and setup the interface. 

Right now we do not offer the ability to disable private networking on a droplet. If you would like to do this we recommend just un-configuring the interface it within your droplet.

**Comment by bob-rove** [comment]
@brookemckim it's OK! At least we'll make it consistent between console and API.

**Comment by macb** [comment]
@bob-rove deployed `enable_private_networking`. Thanks again for the feedback.

**Comment by bob-rove** [comment]
@macb :+1:
