### ISSUE TITLE
Duplicate attribute for Block Storage Volume

### ISSUE THREAD

**Issue by KtorZ** [digitalocean/api-v2#160]
Hey, no big deal but I am reporting it to let you know. The `droplet_ids` field from the Block Storage section is documented twice with subtle differences ^.^

![image](https://cloud.githubusercontent.com/assets/5680256/25942128/3fc88198-363c-11e7-82c4-3f9ab844508e.png)

:+1:

**Comment by andrewsomething** [comment]
Thanks for reporting this issue! :sparkles: I just wanted to let you know that this has been fixed and apologize for the long wait time.
