### ISSUE TITLE
Wrong response body explanation on #create-a-new-block-storage-volume

### ISSUE THREAD

**Issue by yigitozkavci** [digitalocean/api-v2#162]
Documentation stated that response should be a "array called `volumes`", but it's an object with a key `volume` and its value.

Steps to reproduce:
- Go to: https://developers.digitalocean.com/documentation/v2/#create-a-new-block-storage-volume
- See the response explanation: "The response will be a array called volumes containing an object with the standard attributes associated with a volume:"
- See the json response body from right panel
- See that they don't match

**Comment by andrewsomething** [comment]
Thanks for reporting this issue! :sparkles: I just wanted to let you know that this has been fixed and apologize for the long wait time.
