### ISSUE TITLE
Hypertext as the Engine of Application State

### ISSUE THREAD

**Issue by danpalmer** [digitalocean/api-v2#17]
Hey team, well done on the v2 launch.

I noticed that the documentation says "fully RESTful", but support for the "uniform interface" REST constraint looks lacking.

It would be great to see some "HATEOAS" support in the API - I find this is much easier to do with XML/XHTML based APIs, but I realise lots of devs dislike the idea of anything except JSON now. I'd therefore recommend looking at something like JSON+HAL or similar.

**Comment by brookemckim** [comment]
Dan, you are correct our use for the word fully is over overzealous :smile:. 

This is something we considered, but ended up not pursuing for our version 2. If we find enough need we will re-evaluate for a future version of the api.

**Comment by danpalmer** [comment]
Fair enough. I think it's worth the effort, but I am a bit over-zealous about REST myself sometimes.

Could I instead request that "fully" is removed from the documentation. It is really saying to other developers _this is how you design a RESTful API_, when in fact it is missing some crucial components.
