### ISSUE TITLE
Problem with CORS

### ISSUE THREAD

**Issue by PGayol** [digitalocean/api-v2#173]
Hi! I'm trying to send a POST from my Angular app to the API, using the following endpoint:

`https://cloud.digitalocean.com/v1/oauth/token?client_id=MY_CLIENT_ID&client_secret=MY_CLIENT_SECRET&code=MY_CODE'&grant_type=authorization_code&redirect_uri=MY_APP_URL`

On Chrome delevoper tools I can see an OPTIONS request is sent first, and returned with 404, so the POST is never sent.
When I try the same endpoint on https://apitester.com/, I get the response successfully.

Any idea? Thanks!

EDIT: Also tried using Chrome with  `--disable-web-security --disable-gpu` flags and the response is successful, so it looks it's a server-side problem of the API:

**Comment by bentranter** [comment]
I know this issue is pretty old, but in case other folks stumble upon this, I just wanted to share that we're aware of a few misconfigurations with the CORS settings on several endpoints that prevent some requests from going through, and that we're working on getting those issues resolved.

**Comment by PGayol** [comment]
Some time ago I managed to skip this problem by using Nginx as reverse proxy, so the request is made server-side instead of client-side. By, the way, great to know that you are aware of the issue. Thanks!

**Comment by bentranter** [comment]
Hey @PGayol, I know it's been a while, but this was fixed just now 🙂

**Comment by PGayol** [comment]
> Hey @PGayol, I know it's been a while, but this was fixed just now 🙂

Thank you for the update!
