### ISSUE TITLE
Add URN to Database API so they can be added to projects

### ISSUE THREAD

**Issue by IAmNatch** [digitalocean/api-v2#179]
There is currently no way to access a databases URN. Without a URN a database cannot be added to a project.

**Comment by andrewsomething** [comment]
Hi @IAmNatch, 

Thanks for raising this. Databases do in fact have URNs in the format `do:dbaas:<DATABASE_ID>`, but it looks like the API docs do not currently show this. For example, a GET request to a project (`/v2/projects/<PROJECT_ID>/resources`) with a database will include an entry like: 

```
    {
      "urn": "do:dbaas:83c7a55f-0d84-4760-9245-aba076ec2fb2",
      "assigned_at": "2019-06-18T14:12:09Z",
      "links": {
        "self": "https://api.digitalocean.com/v2/databases/83c7a55f-0d84-4760-9245-aba076ec2fb2"
      },
      "status": "ok"
    },
```

We'll get this included in the API documentation.

**Comment by andrewsomething** [comment]
An example has now been added to: https://developers.digitalocean.com/documentation/v2/#project-resources
