### ISSUE TITLE
Ability to look for custom images

### ISSUE THREAD

**Issue by gabriel403** [digitalocean/api-v2#18]
We have a couple of custom built images, it's a pain to have to loop through all images to find them, especially with the pagination in place

**Comment by macb** [comment]
Would you mind elaborating a bit on your use case? Do you just want to be able to filter private images only or did you have more advanced filtering in mind?

**Comment by bob-rove** [comment]
I've made a relevant issue #11.
It's a bit tricky to filter particular type of images (whether it's a distribution, application or image).
In my opinion for these cases something like optional GET-parameters will be very hand:
- type - distro, app or snapshot
- name - image name or a substring

For example:
/v2/images?type={distro,app,snapshot}&name=&lt;query&gt;

**Comment by gabriel403** [comment]
@macb for me I'd just be happy if I could filter private vs public (and maybe vs automatic backup)

**Comment by kjs3** [comment]
++ on this feature.
Being able to request just private images would be enough for me. Then I can filter from there.

**Comment by brookemckim** [comment]
To consolidate I am going to close this in favor of #11
