### ISSUE TITLE
/v2/databases/[id]: database.connection.user does not always return default user

### ISSUE THREAD

**Issue by ehamberg** [digitalocean/api-v2#180]
The `connection` object in the `database` object should contain a `user` key with “the default user for the database”: https://developers.digitalocean.com/documentation/v2/#retrieve-an-existing-database-cluster

From what I understand, this should be the `doadmin` user.

However, it seems to just sort the usernames alphabetically and return the first user. This is both visible on the https://cloud.digitalocean.com/databases/ dashboard (where the “Connection Details” will be for a different user) and – more important – in the API response from the API used by e.g. Terraform.

I hit this issue when I used Terraform's PostgreSQL provider to create a “datadog” role with very limited capabilities. After adding this role, the DigitalOcean API, and thus Terraform's DigitalOcean provider, would attempt to use that user to connect to the database in subsequent calls, which doesn't work.

It should probably always return the `doadmin` user (and password) in the `connection`/`private_connection` objects.

**Comment by andrewsomething** [comment]
Hi @ehamberg,

Thanks for flagging this issue. You are correct; both `database.connection.user` and the “Connection Details” in the control panel should always display the details for the default user. A fix has been put in place, and this should now be resolved.

Please feel free to reopen this issue if you are still able to reproduce the problem.
