### ISSUE TITLE
Sever Error creating database cluster with digital ocean api v2

### ISSUE THREAD

**Issue by aveTakashi** [digitalocean/api-v2#186]
I have been trying to create a database clusters using the digital ocean API v2. 
All i get is server error and the database cluster gets stuck in creating mode and cannot be deleted.

I initially encountered this when applying a terraform IaC script and latter confirmed it by using the digital ocean API v2

**Comment by andrewsomething** [comment]
Thank you for flagging this issue! I am able to reproduce it and have escalated it internally.

**Comment by aveTakashi** [comment]
would be nice if it could be fixed quickly. I ended up creating a number of clusters and don't know if they are accruing charges or not.
