### ISSUE TITLE
Examples for go CDN resources

### ISSUE THREAD

**Issue by g1y** [digitalocean/api-v2#187]
The examples for go on the CDN resources aren't all working for me. It appears they're referencing a struct without referencing the package it belongs to.

```go
flushRequest := &CDNFlushCacheRequest{
    Files: []string{"assets/img/hero.png","assets/css/*"}
}

_, err := client.CDNs.FlushCache(ctx, "19f06b6a-3ace-4315-b086-499a0e521b76", flushRequest)
```
The first line appears to need to be changed to:
```go
flushRequest := &godo.CDNFlushCacheRequest{
...
```

There are a few endpoints that have examples like this one did:
Update an existing CDN endpoint
Purge the cache for an existing CDN endpoint
Create a new CDN endpoint

I really appreciate these examples, so I was excited to hopefully help out. It would be cool if these were also open source so I could submit a PR

**Comment by andrewsomething** [comment]
Thanks for flagging these mistakes! We've pushed an update that should fix them up.
