### ISSUE TITLE
Wrong response type for /droplets

### ISSUE THREAD

**Issue by mazz-seven** [digitalocean/api-v2#189]
Trying to get or create droplets without a token or incorrect token I get text response back instead of JSON.
**Example:** 
GET: https://api.digitalocean.com/v2/droplets
Response: 
content-type: text/plain
Unable to authenticate you

**Comment by andrewsomething** [comment]
Hi @mazz-seven,

Thank you for flagging this behavior. A fix has been deployed, and the error message is now a properly formatted JSON body again:

```
$ curl -X GET -H "Authorization: Bearer notatoken" "https://api.digitalocean.com/v2/droplets" | jq .
{
  "id": "Unauthorized",
  "message": "Unable to authenticate you"
}
```
