### ISSUE TITLE
Domains have un-escaped markup in zone_file

### ISSUE THREAD

**Issue by nraboy** [digitalocean/api-v2#19]
When using /v2/domains I am getting potentially invalid JSON responses due to slashes and characters that should probably not exist in the response.

The zone_file has combinations such as \t or parenthesis which probably shouldn't belong in a JSON response.  For example it is causing AngularJS to fail with invalid token errors.

Have you guys considered replacing the zone_file with an object that contains an array of objects for each cname/aname/etc?  Not only would it be cleaner, but it would make things easier for the developer.

**Comment by brookemckim** [comment]
Thanks @nraboy we are working on this as I type.

**Comment by nraboy** [comment]
Awesome!

I'll keep an eye out for the fix

**Comment by macb** [comment]
@nraboy just deployed a fix from one of our engineers that should resolve this. Closing this for now, feel free to leave feedback if you're still having issues.

Thanks again for the feedback.

**Comment by nraboy** [comment]
Hi @macb,

I am trying to figure out what changed?  Postman for Chrome is still showing a lot of craziness in zone_file and AngularJS is throwing an error when trying to parse the JSON.

Is there any way you can break up the zone_file and use an array of objects rather than one big string with \t characters and new lines?

Cheers,

**Comment by macb** [comment]
@nraboy Ah, needed to bump the cache as well. That should resolve any inability to parse correctly.

If you want an array of objects, I suggest using `/v2/domains/$DOMAIN_NAME/records`. You'll get back an array of domain records which you can then do with as you please.

**Comment by nraboy** [comment]
Hi @macb,

The issue appears to be corrected since having done your cache dump.  I no longer receive parse errors.

I believe it is now safe to close this ticket.

Thanks,

**Comment by macb** [comment]
Great @nraboy. Thanks again for trying things out and we appreciate the feedback.
