### ISSUE TITLE
Create a Read-only Replica docs missing parameter: vpc_uuid 

### ISSUE THREAD

**Issue by JonnyFb421** [digitalocean/api-v2#192]
Hello,
I noticed my read replica was not created in the same VPC as the database cluster, and I was surprised to find that the Digital Ocean Terraform provider does not have an attribute for `private_network_uuid` in the digitalocean_database_replica resource.  Taking a look at the DigitalOcean API docs to see if this limitation was on the Terraform provider or Digital Ocean's API, I found the parameter was undocumented and named inconsistently. 

1. The parameter to specify a VPC UUID is missing from the read replica create endpoint documentation
2. The name of the parameter the read replica creation endpoint accepts is inconsistent with the other database endpoints (`vpc_uuid` vs `private_network_uuid`).

Docs:
https://developers.digitalocean.com/documentation/v2/#create-a-read-only-replica

**Comment by andrewsomething** [comment]
Hi @JonnyFb421,

Thanks for flagging this omission in the docs. We've made an update to the site covering the `private_network_uuid` parameter. I've also submitted a PR to the Terraform provider adding support there. You can track that at: https://github.com/terraform-providers/terraform-provider-digitalocean/pull/440

Regarding the inconsistency in naming, the database endpoints use `private_network_uuid` through out. Which is unfortunate as other endpoints use `vpc_uuid`. I've brought this up with the team, and hopefully this can be addressed in the future.

Thanks for the great feedback!
