### ISSUE TITLE
Database creation returns 422 Error

### ISSUE THREAD

**Issue by nguthrie** [digitalocean/api-v2#194]
Hello, I'm getting a 422 response when trying to create a database with the following API request. 

`import requests`
`from api_token import API_KEY`

`headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer {}'.format(API_KEY),
}`

`data = '{"name": "NG_my_sql_test_db", "engine": "mysql", "version": "8", "region": "nyc3", "size": "db-s-1vcpu-1gb", "num_nodes": 1, "tags": ["script_testing"]}'`

`response = requests.post('https://api.digitalocean.com/v2/databases', headers=headers, data=data)
print(response)`

Any suggestions?

**Comment by rpmoore** [comment]
Cluster names cannot have `_` in them. You can use `-` however.

**Comment by nguthrie** [comment]
Thank you!
