### ISSUE TITLE
Droplet monitoring: Expose REST entry point

### ISSUE THREAD

**Issue by atombrella** [digitalocean/api-v2#195]
https://github.com/digitalocean/terraform-provider-digitalocean/issues/479 The issue is 8 months old. The issue is labelled with "do-api", so some work is required by you to implement that feature.

**Comment by andrewsomething** [comment]
Happy to say that it is now possible to manage monitoring alerts via the API. See:

https://docs.digitalocean.com/reference/api/api-reference/#operation/create_alert_policy
