### ISSUE TITLE
Granular access control through API

### ISSUE THREAD

**Issue by binoykl** [digitalocean/api-v2#197]
Current API access restrictions are 

- read 
- read write. 

Once a privilege is assigned to a user, it automatically allows them to manage everything based on one of the above privileges. It is not possible to make a user only to manage some services programmatically. Today it is "all" or "nothing"

**Comment by nathanjo** [comment]
In 2024, and this is still not possible. Once granted, the API can access everything. It would be better if we could specify services as scopes.

**Comment by andrewsomething** [comment]
Custom scopes for DigitalOcean personal access tokens (PATs) reached generally available April 17th 2024:

**Release Note:** https://docs.digitalocean.com/release-notes/api/#2024-04-17
**Feature Request:** https://ideas.digitalocean.com/interfaces/p/scoped-api-access

**Documentation:**

https://docs.digitalocean.com/reference/api/create-personal-access-token/
https://docs.digitalocean.com/reference/api/api-reference/#section/Authentication
