### ISSUE TITLE
Create multiple API keys and view the secret

### ISSUE THREAD

**Issue by nodesocket** [digitalocean/api-v2#2]
The ability to create multiple API keys, and set a description for each. Also view the secret key. Currently you have to destroy and create a new key if you don't store the secret on your own.

**Comment by joonas** [comment]
> The ability to create multiple API keys, and set a description for each. Also view the secret key. Currently you have to destroy and create a new key if you don't store the secret on your own.

We are definitely planning on providing the ability to create multiple API keys and setting a description for each. I can't yet speak to whether we'll expose the secret keys after they've been created, while I'm of the opinion that they should be treated the same way that passwords are treated (hashed), we'll certainly consider the user experience as well.

Thanks for the feedback!

**Comment by raiyu** [comment]
On the subject of viewing the secret key again:

Our current v1 API does not allow the key to be "viewed" after it is created. We plan to continue with that for v2. The idea is that you would store this key and use it in places, if you have to view it again it probably means that you can't vouch for it being secure anymore in which case we want to err on the side of caution and instead enforce the same policy of having customers re-issue a new key rather than exposing it.

**Comment by nodesocket** [comment]
I've never seen this with any other provider. Stripe shows your API keys forever, Twilio shows API keys forever. Thinking in terms of less security minded users, they most likely are just copying it and putting it in a plain text file. It is actually more secure to show it to them in the control panel. Just my thoughts.

**Comment by brookemckim** [comment]
![screen shot 2014-05-14 at 2 35 44 pm](https://cloud.githubusercontent.com/assets/245680/2975588/955f249e-db96-11e3-9bee-4da25abe6cdd.png)

GitHub does not allow personal access token to be viewed after generation. An access token operates exactly like a password and should be treated as such.

**Comment by nodesocket** [comment]
Sure that is one approach to treat api tokens like passwords, but I am suggesting that a fair amount of DigitalOcean users probably don't store their api credentials in a password manager or secure source. It is convenience/user experience vs security, always a dilemma. I am just advocating that users have an expectation to be able to view their API tokens forever not just when they are generated.

While on the topic, you should allow multiple APi tokens with descriptions, and allow self-destructing tokens (expires in X minutes, X hours, X days).

**Comment by raiyu** [comment]
There is support for multiple tokens with descriptions and the ability to edit descriptions. But in most cases where its user experience vs security we will usually side with security.
