### ISSUE TITLE
Private Networking availability in regions

### ISSUE THREAD

**Issue by fichek** [digitalocean/api-v2#20]
When <a href="https://developers.digitalocean.com/v2/#create-a-new-droplet">creating a droplet</a> we can specify <b>private_networking=true</b> to enable Private Networking for regions where it is available. There should be a way to find out which regions have this capability via API. I suggest simply adding a boolean value to each region in /regions.

**Comment by macb** [comment]
Good call.

**Comment by bob-rove** [comment]
+1, I think it will be great to have such boolean value for **ipv6** as well.

**Comment by fichek** [comment]
@bob-rove +1 on that too.

**Comment by jasonfill** [comment]
On the private networking front...truly private networking would be nice.  Anyone interested in this please vote on it over at http://digitalocean.uservoice.com/forums/136585-digitalocean/suggestions/5490874-add-support-for-a-true-private-network-between-dro.

**Comment by macb** [comment]
Hey @bob-rove and @fichek, we added a key `features` to `Region`. It is an array of available features in that region.
https://developers.digitalocean.com/#regions

```
{
  "slug": "sfo1",
  "name": "San Francisco",
  "sizes": [
    "512mb",
    "1024mb"
  ],
  "available": true,
  "features": [
    "ipv6",
    "virtio",
    "private_networking"
  ]
}
```

Thanks again for the input! Keep it coming.

**Comment by fichek** [comment]
Great, thank you @macb!

**Comment by bob-rove** [comment]
@macb wonderful, thanks !
