### ISSUE TITLE
Add ability to pass virtio feature on droplet creation

### ISSUE THREAD

**Issue by bob-rove** [digitalocean/api-v2#22]
It will make using of droplet features consistent between API and console.
Currently `virtio` feature available via API in region features list but not on droplet creation.

**Comment by raiyu** [comment]
We're deprecating virtio as a toggle-able option because it is now the default going forward, which is why it's removed. One less option for customers to worry about.

**Comment by bob-rove** [comment]
Deprecating `virtio` as a toggle-able option makes sense. By now it's not even possible to know via console whether the droplet is created with `virtio` support or not. So I'll create a new issue to remove this option from features list of a droplet in API.
