### ISSUE TITLE
Cross Origin Scripting / CORS errors

### ISSUE THREAD

**Issue by nraboy** [digitalocean/api-v2#23]
Hi,

I get CORS errors when trying to use certain endpoints.  Since this is a public API, wouldn't it be best to allow cross origin scripting?

JavaScript is throwing complaints, and I'm guessing backend languages might as well.

However, I've been able to get around the JavaScript by making modifications to my browser.

Cheers,

**Comment by macb** [comment]
Which endpoints are you seeing issues with? Any possibility of sharing specific errors?

**Comment by nraboy** [comment]
Strange!

Earlier I was getting these errors with Firefox and Safari on the SSH endpoints, but they appear to have gone away.

The error still exists in Chrome, but if I recall correctly, it's just a bug in Chrome.  The error is as follows:

XMLHttpRequest cannot load file:///home/nraboy/Desktop/DigitalOcean/www/templates/droplets.html. Cross origin requests are only supported for HTTP. 

I wouldn't put to much effort into trying to resolve that one.  Go ahead and close this issue ticket and I'll re-open it if I see it happen again.

Cheers,

**Comment by macb** [comment]
Will do!
