### ISSUE TITLE
/api/v2/actions should be able to handle images actions also

### ISSUE THREAD

**Issue by cristianbica** [digitalocean/api-v2#25]
Haven't played with the droplets API yet but from my testing it seems that the actions created upon a image action (transfer) aren't available in the actions API.

**Comment by macb** [comment]
@cristianbica deployed a fix for this and #26 and closing this as it appears to be resolved. Feel free to leave feedback if you're still having an issue.

Thanks!

**Comment by cristianbica** [comment]
Works now.
One more thing: how about setting the resource_id, resource_type, region fields for image transfer actions? should the the $IMAGE_ID, image, new_region_slug. Do you want me to create a new issue for this?

**Comment by macb** [comment]
Yes, a new issue would be good so anyone else having the same problem can see it in the issue list. Thanks!
