### ISSUE TITLE
Cannot retrieve action details after an image trasfer

### ISSUE THREAD

**Issue by cristianbica** [digitalocean/api-v2#26]
- I `POST` to `/api/v2/images/$IMAGE_ID/actions` with `{type: "transfer", region: "ams1"}`
- I get an `{"action": {...}}` response and I can see in the web interface that the image is transferring

When trying to get the action details to see the progress I get 404 on `/api/v2/images/$image_id/actions/$action_id` or `/api/v2/actions/$action_id`

Might be related to #25

**Comment by ivanvanderbyl** [comment]
Thanks for reporting this @cristianbica, we're looking into it.

**Comment by macb** [comment]
Deployed a fix for this and #25 and closing this as it appears to be resolved. Feel free to leave feedback if you're still having an issue.

Thanks!

**Comment by cristianbica** [comment]
All good. Thanks
