### ISSUE TITLE
Return an error message on images actions

### ISSUE THREAD

**Issue by cristianbica** [digitalocean/api-v2#27]
If I try to transfer an image and it's not possible (because it's not a snapshot or if it's already on that region) the API return an empty body. I should receive http code 422 and the relevant error message

**Comment by macb** [comment]
Thanks @cristianbica, able to reproduce. Will see about a fix.

**Comment by macb** [comment]
Deployed a fix for this @cristianbica. Feel free to leave feedback if you're still having an issue.

Thanks again!
