### ISSUE TITLE
Ability to add and remove public ssh keys to droplets

### ISSUE THREAD

**Issue by nodesocket** [digitalocean/api-v2#3]
An API endpoint to add a public ssh key into an **existing** droplet. Perhaps like:

```
curl https://api.digitalocean.com/v2/droplets/{{droplet-id}}/keys -X POST -d "user=root" -d "public_ssh_key=some-public-ssh-key-here"
```

If the public key already exits in `/home/{{user}}/authorized keys`, return `409 Conflict`, otherwise add the public key into the droplets `/home/{{user}}/authorized_keys`.

Also, an endpoint to remove a public ssh key from an **existing** droplet. Perhaps like:

```
curl https://api.digitalocean.com/v2/droplets/{{droplet-id}}/keys -X DELETE -d "user=root" -d "public_ssh_key=some-public-ssh-key-here"
```

If the public key does not exist in `/home/{{user}}/authorized_keys` return `404 Not Found`, otherwise remove the public key from the droplets `/home/{{user}}/authorized_keys`.

**Comment by joonas** [comment]
Unfortunately this is not an action that we would be able to facilitate through our API, typically something like this is done something else, such as Configuration Management.

**Comment by progrium** [comment]
Though I'd argue that since we manage keys from the beginning, in an ideal world we wouldn't just go hands off once a machine is started. It doesn't actually make sense. Especially in situations where you don't want to want to stand up configuration management. I don't think we should close this one so quickly.

**Comment by nodesocket** [comment]
@joonas If you can inject a public key when you provision a droplet, why not provide the ability to add and delete public keys to already running droplets?

**Comment by lukebarton** [comment]
+1
