### ISSUE TITLE
Ability to get action id after destroy droplet calls

### ISSUE THREAD

**Issue by ghost** [digitalocean/api-v2#31]
Unlike droplet actions like rebooting, resizing, snapshotting destroy droplet command is not considered as an action, therefore there is no action id returning afterwards.
It would be a nice addition to new API.

**Comment by macb** [comment]
Could you expand on your use case for wanting that information? When do you need the status of the destroy?

We are implicitly guaranteeing that a successful request to destroy a droplet will result in the droplet being deleted.
