### ISSUE TITLE
Ability to get actions list by droplet id

### ISSUE THREAD

**Issue by ghost** [digitalocean/api-v2#32]
Getting full action list and filtering it by droplet id is a very cumbersome process.

**Comment by macb** [comment]
Try `GET /v2/droplets/$DROPLET_ID/actions`. I see it is missing an example in our documentation, will see about getting that fixed!

**Comment by ForbiddenEra** [comment]
Thanks OP for pointing this out - would have run into this today or tomorrow.

**Comment by macb** [comment]
thanks again @erkanozsoy, I updated the documentation https://developers.digitalocean.com/#retrieve-actions-for-a-droplet
