### ISSUE TITLE
Add image size for the private images (snapshots or backups)

### ISSUE THREAD

**Issue by bob-rove** [digitalocean/api-v2#33]
It's quite useful to have an image size of the private images in the API.
For example: if the user selects 512mb size for the new droplet we need to disable images (snapshots or backups) with a greater size.

**Comment by brookemckim** [comment]
Bob, would it make sense to provide an array of sizes available for each image?

**Comment by bob-rove** [comment]
I think, getting an array of sizes for each image primarily make sense on the create droplet stage. But, all regions already have a list of available droplet sizes and having just the size of an image makes it trivial to figure out an array of available sizes for selected region and selected image.
Moreover, getting just an image size instead of available image sizes for selected region makes it possible to render a list of snapshots or backups with their image size.
So I think, just a size of an image is more suitable for these reasons than an array of image sizes.

**Comment by brookemckim** [comment]
Ok, sounds good.

**Comment by cybernet** [comment]
+1

**Comment by gabriel403** [comment]
:+1:

**Comment by phillbaker** [comment]
@bob-rove image objects now have `min_disk_size` which correspond to `disk` on size objects. Please see https://developers.digitalocean.com/changelog/api-v2/change-size-to-size-slug/

**Comment by cybernet** [comment]
404 Not Found

**Comment by cybernet** [comment]
https://developers.digitalocean.com/documentation/changelog/api-v2/sizes-available/
