### ISSUE TITLE
Getting data from status.digitalocean.com

### ISSUE THREAD

**Issue by Yorkie595** [digitalocean/api-v2#34]
Would it be possible for us to get any current known issues with DigitalOcean that are posted on https://status.digitalocean.com/?

I could use this to do something that emails me as soon as a new problem crops up with DO.

Even better would be if we could get the following along with each issue:
- The region that the issue affects
- Any updates to the issue
- Opening & closing dates/times of issues
- Type of issue (such as 'Connectivity Issues', 'DNS Issues', 'Email Issues', 'Slow Event Processing' and 'Other' etc)

If you could implement this it would be great!

Thanks!

**Comment by ForbiddenEra** [comment]
+1 not much different than my initial suggestion for adding notifications.

**Comment by brookemckim** [comment]
We provide an RSS feed for status.digitalocean.com (https://status.digitalocean.com/rss). We do not have any plans to integrate that into this API. Let me know if that is what you were looking for.

**Comment by Yorkie595** [comment]
Great, thanks. Didn't notice the RSS feed button on the site.
