### ISSUE TITLE
Slight issue with 'size' error message

### ISSUE THREAD

**Issue by gabriel403** [digitalocean/api-v2#36]
The error message returned from a request when you're not authorised to create that size has a random `Size` at the front.

`Size This size is currently restricted please send an additional payment to unlock.`

Compared to:
`Unable to authenticate you.`
and
`The image you specified is not available in the selected region, you can transfer it to this region from the images pages.`

**Comment by brookemckim** [comment]
Thanks for the report. This is now fixed.

**Comment by ankitchiplunkar** [comment]
I have recently come across the same error
What should I do?
![digitaloceanerror](https://cloud.githubusercontent.com/assets/5904910/10251438/f9ae6954-6930-11e5-961a-26a28cc15271.png)

**Comment by ZFYL** [comment]
The same here, however i prepaid 50 US Dollars! This is type a scam from DigitalOcean?
