### ISSUE TITLE
403 vs 401

### ISSUE THREAD

**Issue by gabriel403** [digitalocean/api-v2#37]
When a token is read only you return the same error status as when a request is unauthorised, ie incorrect token. I think it would be a good idea to differentiate the two in the returned json and http status code. 

403 vs 401
permission_denied vs unauthorised

also it's kinda backwards to have 401 with the return json of `{"id":"unauthorized","message":"Unable to authenticate you."}`

401 should be unauthenticated and 403 unauthorized

**Comment by bob-rove** [comment]
+1

**Comment by macb** [comment]
The `id` field corresponds with the http status codes, so `unauthorized` is the correct `id` for 401.

The `message` could definitely be improved in the case of our `401 Unauthorized` responses.

I agree, we could be a bit more explicit in cases where the token's scopes don't allow for that request with a `403 Forbidden`, though I'm not sure when that change will make it in.

**Comment by gabriel403** [comment]
I'd argue that 401 is intended to be for missing or incorrect authentication credentials and 403 is accessing something or a method you don't have permission to, reading a droplet you don't have access to, or creating a droplet when you are using a ro token.

But tbh I'm just happy to get a differing status code/id so I can show different error pages ;)
https://dom.prowl.io/images/401.gif

**Comment by macb** [comment]
I agree, `401` is intended for missing/incorrect credentials.

I should clarify, assuming we make this change, it would only be for authenticating against the route, meaning if you use a read-only token and try to use a route that requires the write scope, you would get back a `403`.

All instances where the API `404`'s, it will continue to do so (such as trying to create a domain record for a domain the account does not have access to).

**Comment by brookemckim** [comment]
This has been resolved. 403 is now returned when using a valid token with an invalid scope.
