### ISSUE TITLE
Getting password and balance

### ISSUE THREAD

**Issue by repman** [digitalocean/api-v2#4]
We've been waiting for a new version of API, but have not seen her in two very important functions for us:

1) Get a password when creating a new droplet or reinstall it 
2) Get money balance

**Comment by index0h** [comment]
+1

**Comment by Yorkie595** [comment]
Being able to get your balance would be a nice feature.

**Comment by brookemckim** [comment]
As of right now we will not be offering password. As for balance we do have plans to expose account information, but are still working on the specifics internally.

**Comment by CMCDragonkai** [comment]
Any progress on this? All the other issues on getting invoices were closed. And it's been over a year since the last reply.

**Comment by livenson** [comment]
Same question. Billing API would be very much appreciated.

**Comment by kgroveshok** [comment]
And here too please.

**Comment by rebelweb** [comment]
+1

**Comment by jibsaram** [comment]
+1

**Comment by poratGalpo** [comment]
+1

**Comment by kostasx** [comment]
+1

**Comment by ale26** [comment]
+1

**Comment by Majesko** [comment]
+1

**Comment by ale26** [comment]
+1

**Comment by DaHaiz** [comment]
+1
