### ISSUE TITLE
images across regions not showing all regions

### ISSUE THREAD

**Issue by gabriel403** [digitalocean/api-v2#42]
In the UI I have transfered an image between regions, but it's only showing under the one region in the api.

![screenshot 2014-07-02 15 38 49](https://cloud.githubusercontent.com/assets/118638/3457245/0def9052-01f7-11e4-88d3-1c32095c020c.png)

```
    {
      "id":"redacted",
      "name":"prowl",
      "distribution":"Ubuntu",
      "slug":null,
      "public":false,
      "regions":[
        "ams2"
      ],
      "created_at":"2014-01-23T20:11:15Z"
    }
```

**Comment by brookemckim** [comment]
Thanks. I will get this fixed up.

**Comment by gabriel403** [comment]
@brookemckim I've noticed some work on this (seeing all regions an image is in, but original one is  duplicated) any idea when this will be finished?

**Comment by brookemckim** [comment]
@gabriel403 This is fixed now. Let me know if you are still seeing any issues.
