### ISSUE TITLE
Feature: Add option for retrieving unlimited objects for single response

### ISSUE THREAD

**Issue by rahilwazir** [digitalocean/api-v2#43]
I've asked a [question](https://www.digitalocean.com/community/questions/change-total-limit-for-droplet-images-response).

There should be an value like `-1` for `per_page` to get unlimited Droplets or Images response (_no `page` navigation or so_). Just all the objects in single response. I can set larger numbers for now, like `1000`.

**Comment by macb** [comment]
`per_page` wasn't intended to allow a user to return an unlimited number of droplets or images. Like you said, currently you can set an arbitrarily large `per_page`, but that may have a limit on it in the future.

**Comment by brookemckim** [comment]
We will actually be enforcing a maximum `per_page` size.
