### ISSUE TITLE
Missed "Take a snaphot" action

### ISSUE THREAD

**Issue by bob-rove** [digitalocean/api-v2#47]
The new version of the API doesn't have "Take a snapshot" endpoint. It seems, like it was missed (or I wasn't able to find this action in docs), because the previous version of the API does have - https://developers.digitalocean.com/v1/droplets/#take-a-snapshot

**Comment by brookemckim** [comment]
Hey Bob, this was missing initially, but is in there now https://developers.digitalocean.com/#snapshot

**Comment by bob-rove** [comment]
Thanks! Sorry, it's just the docs page in my browser was out of date :) :+1:
