### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by GrahamCampbell** [digitalocean/api-v2#48]
The "started_at" and "completed_at" properties on the "Action" model are described as being of type "integer", but surely they should be of type "string" if they have a value of "2014-07-07T20:07:15Z" for example.

**Comment by ivanvanderbyl** [comment]
Well spotted, this is typo in the docs. They should correctly be a string containing an ISO8601 formatted date.

**Comment by brookemckim** [comment]
@GrahamCampbell thank you for catching this. It is now fixed.

**Comment by GrahamCampbell** [comment]
Great. :)
