### ISSUE TITLE
Response body when deleting a droplet

### ISSUE THREAD

**Issue by blom** [digitalocean/api-v2#5]
When deleting for instance an image, the image properties are returned in the response body. When deleting a droplet, no response body is present currently. It would be great if droplet delete would have a response body since the other resources do when they are being deleted.

What do you guys think?

**Comment by joonas** [comment]
Hey @blom, that's definitely a great point, we need to make our API responses consistent between resources. Before we go one way or another, I would like to understand what's your use case for this?

From the simplicity point of view, we should be returning `204` with an empty body, but if you have a use case in mind for this, then we may have to reconsider.

**Comment by blom** [comment]
Hi, @joonas! I don't have a specific use case - just what you said about keeping it consistent. 204 with an empty body is good in my view.

Really liking the new API, by the way!

**Comment by joonas** [comment]
Great, that's good to hear!

We'll definitely make sure it's consistent across resources, will update this thread once we've had a chance to make it so.

Thank you for the feedback!

**Comment by macb** [comment]
@blom Thanks for the feedback. I standardized on `204` and an empty body. Deployed it earlier today.

**Comment by blom** [comment]
@macb Very nice. Thank you!
