### ISSUE TITLE
Check if backups enabled

### ISSUE THREAD

**Issue by gabriel403** [digitalocean/api-v2#50]
There appears no way to know if backups are enabled or not, also there's an action to disable backups, but not enable them, it would be nice to be able to enable them.

**Comment by GrahamCampbell** [comment]
It would be simple to have it as a property on the droplet object?

**Comment by gabriel403** [comment]
Indeed

**Comment by macb** [comment]
Good catch. Simple enough. Will discuss this on Monday.

**Comment by brookemckim** [comment]
This has been addressed by adding an array that lists all the enabled features for a Droplet.
https://developers.digitalocean.com/#droplets

Currently backups can not be enabled on a droplet after create time.
