### ISSUE TITLE
Domain request always returns null for zone_file

### ISSUE THREAD

**Issue by gabriel403** [digitalocean/api-v2#51]
Listing domains always returns null for the zone_file

```
{
  "domains":[
    {
      "name":"butts.com",
      "ttl":1800,
      "zone_file":null
    }]
```

But doing requests for `/v2/domains/butts.com/records` does return me records as expected. 

The only reason I'm looking at the `zone_file` is as an indicator of whether the DNS has initially propagated to the DO DNS servers.

**Comment by brookemckim** [comment]
Thanks Gabriel, will take a look.

**Comment by brookemckim** [comment]
@gabriel403 this is fixed. Let me know if you still have issues.
