### ISSUE TITLE
images in api json that don't exist

### ISSUE THREAD

**Issue by gabriel403** [digitalocean/api-v2#53]
There are some private images coming through in the images json that don't exist. When creating a droplet from these images the post request is fine but upon getting the list of droplets the new one doesn't exist. When going into the DO site proper the image isn't listed anywhere, it's only appearing via the api.

**Comment by gabriel403** [comment]
I should say these are backup images `servername 2014-06-29`

**Comment by brookemckim** [comment]
Gabriel, do you have the action_id that was returned when you created the Droplet?

**Comment by gabriel403** [comment]
@brookemckim did a new one just for you 

```
    "action_ids":[
      28748069
    ]
```

**Comment by brookemckim** [comment]
Thanks. I will look into this along with all your other open issues today :smile:.

**Comment by gabriel403** [comment]
:D I'll find some more to keep you busy :)

**Comment by gabriel403** [comment]
@brookemckim any news on this?

**Comment by brookemckim** [comment]
sorry @gabriel403 was on vacation last week :smile:. I will get to this today!

**Comment by brookemckim** [comment]
@gabriel403 I see the problem. We will work on fixing ASAP.

**Comment by gabriel403** [comment]
:+1:

**Comment by brookemckim** [comment]
OK @gabriel403 this has been fixed! Sorry for the huge delay. Let me know if you continue to see problems.
