### ISSUE TITLE
regions request should return all regions

### ISSUE THREAD

**Issue by gabriel403** [digitalocean/api-v2#54]
There's an `available` flag on the response object so it doesn't make sense to not return all regions. 
I think images can be transferred to any region despite them not being available for new droplets so being able to get all regions would be good!

**Comment by fichek** [comment]
I'm almost certain the regions api _did_ return all regions when I first tried it a few weeks ago. But yeah, now it doesn't and I agree that's the way it should work.

**Comment by phillbaker** [comment]
There's a fix in the pipeline. We'll update this issue when it's shipped. Thanks!

**Comment by phillbaker** [comment]
This has been fixed, all regions are returned with an available property in the response.
