### ISSUE TITLE
Where's API to convert image to snapshot?

### ISSUE THREAD

**Issue by liverbool** [digitalocean/api-v2#55]
I can't find API to convert backup droplet image into snapshot. It exists or not?
![screenshot jul 17 15 30 06](https://cloud.githubusercontent.com/assets/206804/3610547/c80e50da-0d8d-11e4-9161-d77d55be262f.png)

**Comment by gabriel403** [comment]
AFAIK droplet backups are just a type of image you can use as a source for a new droplet, just like snapshots

**Comment by liverbool** [comment]
@gabriel403 Thanks, But i'm not sure about `pricing` between backup and snapshot image.

> https://www.digitalocean.com/community/tutorials/digitalocean-backups-and-snapshots-explained
> Snapshots and Backups Pricing
> The pricing for backups is 20% of the cost of the virtual server. So if you want to enable backups for a $5/mo virtual server, the cost for backups will be $1/mo.
> The price for snapshots will be $0.02 per GB of snapshot storage per month.

What's do you think about this?

**Comment by brookemckim** [comment]
You are correct, this functionality is not yet in the API, but will be added. 

@gabriel403 backups are also automatically purged. Converting to a snapshot will keep the image around until you decide to delete it.

**Comment by phillbaker** [comment]
This was released https://developers.digitalocean.com/documentation/changelog/api-v2/add-image-convert/.
