### ISSUE TITLE
Oauth tokens are not persisted

### ISSUE THREAD

**Issue by yassirh** [digitalocean/api-v2#56]
If i follow the url bellow and grant my application read rights and then use the generated oauth token it can't do read operations. 

`https://cloud.digitalocean.com/v1/oauth/authorize?client_id=<client_id>&redirect_uri=<callback url>&response_type=code`

Here is what i get as a response : `{bearer=WWW-Authenticate: Bearer realm="DigitalOcean", error="invalid_token", error_description="The access token is invalid"}`

when i look into "Authorized Applications" in the control panel nothing is added to it.

**Comment by gabriel403** [comment]
@yassirh that's the v1 api, this is for v2, https://developers.digitalocean.com/v2/

**Comment by yassirh** [comment]
@gabriel403 i don't think so given that the url is what i get when created my application on the DO dashboard...

**Comment by gabriel403** [comment]
@yassirh that applications section would appear to still be using the v1 api, hence getting the seperate client id and secret strings, the reference for the v1 of the api is https://developers.digitalocean.com/v1/

**Comment by phillbaker** [comment]
@yassirh you'll have to use a full OAuth authentication flow for authenticating applications - we're working on documentation for the applications section, but the spec is here: http://tools.ietf.org/html/rfc6749. We'll potentially release libraries for select languages.

@gabriel403 it is actually part of the new API, it's confusingly named since it's the first OAuth endpoint on our control panel application.

**Comment by phillbaker** [comment]
@yassirh this is an article explaining integration with the Oauth2 protocol: http://aaronparecki.com/articles/2012/07/29/1/oauth2-simplified. We'll also have DO specific documentation coming out shortly. If you do find problems using the protocol, please let us know.

**Comment by phillbaker** [comment]
@yassirh please also see https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2.

**Comment by yassirh** [comment]
@phillbaker thank you!

**Comment by Ajnasz** [comment]
Hey!

I'm trying to authenticate using the community tutorial, but when I send post requerst to /v1/oauth/token I get a 200 response but with empty body.

Am I doing something wrong?

**Comment by Ajnasz** [comment]
On Mon, Jul 21, 2014 at 11:31:20AM -0700, Hannoun Yassir wrote:

> @Ajnasz You should do a POST request.

It is a post request to https://cloud.digitalocean.com/v1/oauth/token.

The content type is "application/x-www-form-urlencoded; charset=UTF-8"

The request body is

code=AUTH_CODE&client_id=CLIENT_ID&client_secret=CLIENT_SECRET&redirect_uri=MY_CALLBACK_URI&grant_type=authorization_code

All values are replaced to the correct values.

**Comment by Ajnasz** [comment]
I found that the issue was that I tried to send the request with XMLHttpRequest, but this call does not support cors.. I only tested my code with it, but anyway I should move this call into server side, to keep client secret secret.

What I can't find is what are the valid scopes? I need read/write access.

Thanks!

**Comment by yassirh** [comment]
@Ajnasz Here is a php script i used to get the token : 

```
<?php 
$code = $_GET['code'];
$clientId = "<client id>";
$clientSecret = "<client secret>";
$redirectionUrl = rawurlencode("<redirection url>");
$url = sprintf("https://cloud.digitalocean.com/v1/oauth/token".
"?client_id=%s&client_secret=%s&grant_type=authorization_code&code=%s&redirect_uri=%s", 
$clientId, $clientSecret, $code, $redirectionUrl);

$fields = array();
$fields_string = "";
$ch = curl_init();
curl_setopt($ch,CURLOPT_URL, $url);
curl_setopt($ch,CURLOPT_POST, count($fields));
curl_setopt($ch,CURLOPT_POSTFIELDS, $fields_string);
curl_setopt($ch,CURLOPT_RETURNTRANSFER, TRUE);

$result = curl_exec($ch);
curl_close($ch);

$json = json_decode($result, TRUE);

var_dump($json);
```

All you have to do point your redirect url to run this script. I hope it helps.

**Comment by yassirh** [comment]
@Ajnasz YOUR_URL&scope=read write

**Comment by Ajnasz** [comment]
@yassirh That is, thanks!
