### ISSUE TITLE
Oauth doesn't return a refresh token

### ISSUE THREAD

**Issue by yassirh** [digitalocean/api-v2#57]
When the access is granted we only get access token that expires in a couple of hours. but no refresh token to renew the access token. any chance it would become mandatory in the response?

**Comment by phillbaker** [comment]
Yes, otherwise, users of apps will have to re-authenticate every 2 hours. :grinning: That's no fun.

I'll update this issue, when I have more info.

**Comment by yassirh** [comment]
@phillbaker indeed no one would use that kind of app :) keep up the good work!

**Comment by phillbaker** [comment]
We've added refresh tokens to the auth result and token expiration is now set to 30 days. Thanks @yassirh.

**Comment by yassirh** [comment]
Seems good! thanks for the quick fix.
