### ISSUE TITLE
API that will return the user info?

### ISSUE THREAD

**Issue by k1ngpr4wn** [digitalocean/api-v2#61]
Is there a URL that will return the user info when given an access_token? i.e. GitHub's is https://api.github.com/user, and Google's is https://www.googleapis.com/oauth2/v1/userinfo

**Comment by macb** [comment]
I was waiting for this issue to show up. Yes, we discussed exposing some amount of user information, but we haven't settled on what exactly. It will be added, though there is no estimated date currently.

I'd love to hear what information would be useful to you and why.

**Comment by k1ngpr4wn** [comment]
This question was prompted by me trying to implement your OAuth2 API into the titarenko/OAuth2 GitHub project, but I'm certainly no expert in OAuth2.

I suppose it may just be a way to separate concerns, so when the token is returned, it wouldn't need to send the user info, and another request would be made to get it, and could include more information, maybe some contact information for the user themselves (i.e. what's shown in your Contact Information section at https://cloud.digitalocean.com/settings/account, but of course that might be another "scope" that the token could permit access to).

**Comment by phillbaker** [comment]
Related to https://github.com/digitaloceancloud/api-v2/issues/4 (first issue that falls under this scope).

**Comment by phillbaker** [comment]
This has been released, documentation for it can be found at https://developers.digitalocean.com/#account. Note that we haven't introduced further scopes (like for billing permissions), so the information exposed is limited, in the future, we may introduce more finely grained scopes that will allow additional information to be exposed.

**Comment by dkapanidis** [comment]
Great, now we can use DigitalOcean oauth as our signup button form directly and get the account info from here.

A slightly related question, if such a workflow makes unregistered users signup on DigitalOcean will this be added to the referral program?

**Comment by repman** [comment]
Get money balance?

**Comment by kgroveshok** [comment]
Yes account balance would be awesome. Any movement on this?
