### ISSUE TITLE
OAuth2 Refresh Token

### ISSUE THREAD

**Issue by zarakay** [digitalocean/api-v2#62]
This may not be perfect place to put this, but in regards to the new completed OAuth2 api. The tutorials which was referenced in the email shows correctly how to get the access token using OAuth2. The response includes a refresh token. They do not specify the url to send requests to in order to use the refresh tokens. 

Any help on how to use the refresh token would be appreciated.

**Comment by k1ngpr4wn** [comment]
I have not confirmed this, but check out the OAuth2 spec (http://tools.ietf.org/html/rfc6749#section-6) it seems that you send that request to https://cloud.digitalocean.com/v1/oauth/token as indicated.

**Comment by zarakay** [comment]
I had a look as you specified and it seems you were correct, you just use the same url. The reason for the confusion is that some websites have their own refresh url. Thanks for the help!
