### ISSUE TITLE
Mobile-friendly authorization page

### ISSUE THREAD

**Issue by fichek** [digitalocean/api-v2#63]
Not exactly API issue, but related and definitely an issue. I know none of the DigitalOcean web pages are optimized for mobile, but this is one that should be easy enough to do and would benefit mobile apps' ux a lot. Currently being redirected from a nicely designed mobile app to a zoomed out page like this is simply not acceptable:

![current](https://cloud.githubusercontent.com/assets/956646/3709001/4b624e76-144d-11e4-86a4-ec02698f0fc5.png)

Quick mockup of a possible solution:

![example](https://cloud.githubusercontent.com/assets/956646/3709002/4b680bae-144d-11e4-862e-b353a4625920.png)

**Comment by macb** [comment]
hey @fichek I'll get this in front of our design team. Thanks!

**Comment by nraboy** [comment]
Hi @macb, I agree with @fichek, but I'd like to add to this.

The sign in page should be mobile friendly as well as the authorization page.  On top of this, the two step token page should be mobile friendly as well.

Thanks,

**Comment by fichek** [comment]
@nraboy indeed!

**Comment by nraboy** [comment]
Hi @macb,

I was wondering if any progress has been made on this?  I'd love to be able to use Oauth in my application, but it needs to be optimized for mobile.

Thanks,

**Comment by ivanvanderbyl** [comment]
Hi @nraboy our front-end team is working on this at the moment, it should make it into production soon.

**Comment by fichek** [comment]
Nice new responsive <a href="https://www.digitalocean.com">homepage</a>, I hope login and OAuth pages receive similar treatment soon.

**Comment by nraboy** [comment]
@fichek Agreed!

**Comment by ChasingUX** [comment]
Updated Screens:

![a37eee40-3787-11e4-80b1-e711d0f37b52](https://cloud.githubusercontent.com/assets/5446551/4276177/03fee31c-3d03-11e4-8c38-9a7a0029728d.png)
![a380749a-3787-11e4-88c1-00951fbea657](https://cloud.githubusercontent.com/assets/5446551/4276178/04038f20-3d03-11e4-9964-c946bcd2cccf.png)
![a37e877a-3787-11e4-9d9c-fd59cd7acb9f](https://cloud.githubusercontent.com/assets/5446551/4276179/04061402-3d03-11e4-808a-6394f2f3fcf6.png)

**Comment by ivanvanderbyl** [comment]
:+1:

**Comment by fichek** [comment]
@jesseDO looks great! Any ETA for it going live? Will the login page be updated too?

**Comment by ChasingUX** [comment]
@fichek this should go live later this week. Will also work on the login screen as well.

**Comment by fichek** [comment]
@jesseDO actually, looks like it's live already, but is missing `<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">` to make it scale properly on mobile.

Here's a screenshot from my resized desktop browser:

![screen shot 2014-09-15 at 20 16 01](https://cloud.githubusercontent.com/assets/956646/4276365/9699e374-3d04-11e4-95d8-f151718f879e.png)

And another screenshot from iOS Simulator:

![ios simulator screen shot 15 sep 2014 20 18 36](https://cloud.githubusercontent.com/assets/956646/4276396/d5fc47aa-3d04-11e4-98f1-58bf7cbaa1de.png)

**Comment by ChasingUX** [comment]
@fichek this will be shipped shortly :)

**Comment by joonas** [comment]
Closing this out since it's been completed, thanks @fichek & @jesseDO :+1:

**Comment by fichek** [comment]
@jesseDO @joonas didn't want to open a new issue for something this small and very much related, so here it goes:

The new signin/signup page has no bottom padding on the footer which makes it really hard to tap the link it contains on a touch screen. 

Example from iPhone: when bars are hidden, the sign up button is super-close to bottom of the screen, so tapping it brings up the bars instead of activating the link.

![ios simulator screen shot 06 mar 2015 18 51 11](https://cloud.githubusercontent.com/assets/956646/6530540/fd8337a2-c431-11e4-902b-ea7b4bcc9397.png)

![ios simulator screen shot 06 mar 2015 18 52 04](https://cloud.githubusercontent.com/assets/956646/6530541/fdad8a3e-c431-11e4-90ed-513b8c79e1b1.png)

Trying to tap the link when bars are visible can also lead to accidentally tapping bookmarks/tabs buttons in the bottom toolbar since they are so close.

**Comment by ChasingUX** [comment]
@fichek we will address this

**Comment by joonas** [comment]
@fichek - thank you for reporting this, as @jesseDO already mentioned, we'll be sure to address this!
