### ISSUE TITLE
Read and write scope value for OAuth

### ISSUE THREAD

**Issue by deivuh** [digitalocean/api-v2#65]
Hi, 

I would like to know what's the value for the authorization code link's scope variable for both read and write access. 

I have read both the [DigitalOcean API v2 tutorial](https://www.digitalocean.com/community/tutorials/how-to-use-the-digitalocean-api-v2) and the [Introduction to OAuth 2](https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2), and the possible values are not listed anywhere. The examples shown all pass the '_read_' scope, and I've verified '_write_' works for write only. I have also tried '_read-write_' and '_read/write_' with no luck. 

Edit: Nevermind, I've just checked out your other repository, [omniauth-digitalocean](https://github.com/digitaloceancloud/omniauth-digitalocean) and saw that it's "_read write_" it would be great to have it documented on any of the mentioned articles.

**Comment by macb** [comment]
OAuth 2 scopes are space separated so: `read write`. I do agree that we could better document this fact.

**Comment by raiyu** [comment]
We'll get the docs updated, thanks for pointing this out.

**Comment by phillbaker** [comment]
This has been documented here: https://developers.digitalocean.com/oauth/#scopes. Thanks for opening an issue!
