### ISSUE TITLE
How to enable backups for droplet?

### ISSUE THREAD

**Issue by jeevatkm** [digitalocean/api-v2#67]
I'm able to see <code>disable_backups</code> under [Droplet Actions](https://developers.digitalocean.com/#disable-backups).

Now to enable it again?

**Comment by jeevatkm** [comment]
For the note, v1 API had a <code>enable_backups</code> action for droplet.

**Comment by phillbaker** [comment]
Hi @jeevatkm, we presently only allow disabling of backups after a droplet create.
