### ISSUE TITLE
Documentation index with link anchors

### ISSUE THREAD

**Issue by deivuh** [digitalocean/api-v2#7]
Not a request for the API, but for the documentation itself. 

While this might be a temporal location for the documentation, it would be helpful to have an index at the start with anchor links to each section, being this an extensive documentation.

**Comment by ivanvanderbyl** [comment]
@deivuh we'll be rolling out new documentation very shortly with our v2 roll out. I'll update this ticket when we have a link.

**Comment by macb** [comment]
@deivuh the new v2 docs are available at https://developers.digitalocean.com/v2/ for now. This is also a temporary location as we bring the API toward a wider release.

Hopefully it's a bit easier to navigate.

**Comment by deivuh** [comment]
Great! Thank you
