### ISSUE TITLE
code based, non-redirect auth flow

### ISSUE THREAD

**Issue by max-mapper** [digitalocean/api-v2#70]
(firstly, this page has very little useful information on it: https://developers.digitalocean.com/ and should really link to this one: https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2)

it would be nice to have an auth flow for e.g. CLI authorization or other non-web based flows

example:
1. CLI program prints `Open the following URL in your browser, then paste the resulting authorization code below:` with a link to the digitalocean auth endpoint
2. user auths in their browser, gets a e.g. 6 digit code
3. they copy paste the code into the terminal. now the CLI program can use that to get an access token

**Comment by phillbaker** [comment]
@maxogden we have more descriptive, technical docs for https://developers.digitalocean.com/ coming out shortly! Thanks for the interest.

As for a non-web based flow, we are looking at the different options for supporting CLIs and mobile apps. For the mean time, it seems like a CLI could use a personal access token? (Available here: https://cloud.digitalocean.com/settings/tokens/new)

**Comment by phillbaker** [comment]
@maxogden please see https://developers.digitalocean.com/oauth/, any feedback would be appreciated.
