### ISSUE TITLE
Get IP address of server on creation

### ISSUE THREAD

**Issue by martinalderson** [digitalocean/api-v2#73]
Is there any way to have some way to get the IP address of the droplet when creating it? Right now I am just polling after creation to get the IP which isn't ideal.

**Comment by brookemckim** [comment]
Unfortunately at the time we return the response the IP Address is not yet known. That is part of the droplet provisioning process.

**Comment by martinalderson** [comment]
Hi, I understand that. Would you recommend I just continue polling the API until the server has actually been created? Or is there some other design pattern you would use here?

**Comment by martinalderson** [comment]
Ideally a param like 'waitUntilProvisioned: true' would be ideal in the rqeuest body, that would keep the api response open until you've got the IP of the droplet.

**Comment by brookemckim** [comment]
Right now polling is your best bet. We are working on different approaches such as webhooks and response streaming.

**Comment by lliamscholtz** [comment]
Hi @brookemckim - Has there been any implementation yet regarding this request? I'm in the situation at the moment where I'd like to use the API to create a droplet and then, after provisioning,  assigning an A name record immediately (which requires the new droplets IP address). Thanks
