### ISSUE TITLE
Developer accounts or mock server library for testing integrations

### ISSUE THREAD

**Issue by changhiskhan** [digitalocean/api-v2#75]
I have to use my own account for running unit tests. Instead it would be great if there was a standing developer account OR a mock server library so integrations can be automatically tested on open-source CI tools like Travis-CI

**Comment by phillbaker** [comment]
Related to #40, we're considering the best way to support integration testing. Thanks for the input!

**Comment by mkarnicki** [comment]
I'm just familiarizing myself with all the bugs before I use the API. If this is tracked in #40, perhaps this one should be closed?

**Comment by andrewsomething** [comment]
Closing in favor of https://github.com/digitalocean/api-v2/issues/40
