### ISSUE TITLE
Droplets / DropletActions dichotomy unintuitive

### ISSUE THREAD

**Issue by changhiskhan** [digitalocean/api-v2#76]
I think the dividing line should be collection vs units. For example, getting kernels/backups/snapshots etc for a single droplet belongs to the "Droplets" resource but generally performing actions belong to "DropletActions". This seems counter-intuitive to me. Instead it should start with the collection, get a unit, then examine the unit for details or affect some change on the same unit.

**Comment by phillbaker** [comment]
@changhiskhan can you elaborate on this? We're not quite sure what you're suggesting.

**Comment by phillbaker** [comment]
Hi @changhiskhan if you could elaborate more on this, please re-open the issue, otherwise, I'll close it for now.
