### ISSUE TITLE
API for the droplets limit

### ISSUE THREAD

**Issue by bob-rove** [digitalocean/api-v2#77]
It will be great to know the limits before creating a droplet via API. Especially creating several droplets at once via API.
This could be a part of the user info - #61 .

**Comment by GrahamCampbell** [comment]
Yeh, so the maximum droplet size, the max number they can create, and the regions they are allowed to create them in would be really cool.

**Comment by bob-rove** [comment]
In particular, I meant the droplets max number, that visible only on the settings page in the web-console.
Region availability is already a part of another API endpoint - https://developers.digitalocean.com/#regions
As of the maximum droplet size - as I understand - this is the part of the droplets distribution algorithm, which is evaluating, when you are about to create a new droplet. The bad thing in the droplet resize action (at least for now) is that you can't distinguish via API which size is the maximum allowed, because once created, the droplet is bound to the host machine forever and even during several minutes the max size could change (eg.: if someone's new droplet will be placed on the same host).
This is no true when you are about to create a new droplet, because the host at this moment is not determined and will be chosen upon the size of the droplet you select.
I've just created an issue #78 to get available droplet sizes before resize.

**Comment by phillbaker** [comment]
This is related to #61, this will likely be included in that feature.

**Comment by fichek** [comment]
I accidentally noticed this in the docs a few days ago: https://developers.digitalocean.com/#account

**Comment by phillbaker** [comment]
@fichek yes, this has been implemented at that endpoint.
