### ISSUE TITLE
Available droplet sizes via API (to use before resize action)

### ISSUE THREAD

**Issue by bob-rove** [digitalocean/api-v2#78]
As mentioned in #77 it will be great to have an API returning available droplet sizes before attempting to resize a droplet to a bigger size than allowed.
This feature already available via web-console, but not via API.

**Comment by fichek** [comment]
Looks like `/sizes` now only returns the sizes available to authenticated user. I don't know if this was intended or what, but it's a bit weird. I think what `/regions` does would work here too - list all the existing sizes and have an `available` field on each.

**Comment by phillbaker** [comment]
@bob-rove in most DigitalOcean regions, we now allow resize to any size available for that user. We'll be expanding this to all regions over the coming months.

@fichek sizes now expose an available attribute: https://developers.digitalocean.com/documentation/changelog/api-v2/sizes-available/.

**Comment by fichek** [comment]
@phillbaker great, thank you!
