### ISSUE TITLE
Need droplet statistics

### ISSUE THREAD

**Issue by stuartpb** [digitalocean/api-v2#80]
I'm looking to make a public sandbox machine with root access for users to try [Plushu](https://github.com/plushu), and I want to set up a watchdog that will reset the server if disk usage, CPU usage, or transfer exceed a reasonable limit.

**Comment by phillbaker** [comment]
@stuartpb thanks for the input. This is very similar to https://github.com/digitaloceancloud/api-v2/issues/12, which is planned, however, doesn't have a definitely release date yet.

In the meantime, it seems like an hourly reset of the box might work?
