### ISSUE TITLE
QR codes for personal access tokens

### ISSUE THREAD

**Issue by dan-abc** [digitalocean/api-v2#81]
It would be great if a QR code is shown when a personal access token is created so mobile app users could hold their up phone to authenticate instead of having to copy the code.

**Comment by phillbaker** [comment]
@dshepherd that's a cool idea, thanks! Since this isn't two factor auth, do you have any links to specs or any common ways that other folks have implemented this?

**Comment by danielgolub** [comment]
@phillbaker You can use a PHP QR code generator script (like http://www.shayanderson.com/php/php-qr-code-generator-class.htm), and create a secret hash (e.g. cloud.digitalocean.com/secret/SDJ-+-213==-SD()@!#D) which will grant access to the user.

**Comment by brookemckim** [comment]
We do not have any plans to support this at the moment, but I will leave the issue unlocked to allow further discussion.
