### ISSUE TITLE
API v2 release date? and CHANGELOG.md update

### ISSUE THREAD

**Issue by jeevatkm** [digitalocean/api-v2#82]
I would like to know the API v2 release date also required [CHANGELOG.md](https://github.com/digitaloceancloud/api-v2/blob/master/CHANGELOG.md) file update. This file was updated a month ago.

**Comment by phillbaker** [comment]
Hi @jeevatkm we don't have a specific release date yet, but we'll announce publicly when we feel comfortable ending the beta and locking in the schema of the API. This will probably be "soon" (TM) :grinning: !

**Comment by jeevatkm** [comment]
Thanks @phillbaker, how about updating CHANGELOG.md?

**Comment by phillbaker** [comment]
https://github.com/digitalocean/api-v2/blob/master/CHANGELOG.md has been updated. Thanks!
