### ISSUE TITLE
Recommendation: RateLimit values in JSON response instead of HTTP Header values

### ISSUE THREAD

**Issue by jeevatkm** [digitalocean/api-v2#83]
Having a ratelimt values in JSON response would be more meaningful. It is meta information about every  API request.

having as part of <code>meta</code> info:

<pre>
...
"meta": {
     "total": 10,
     "rateLimitCap": 1200,
     "rateLimitRemaining": 1191,
     "rateLimitReset": "2014-06-02T14:06:53Z"
}
...
</pre>

OR

having separate node as <code>rateLimit</code> at <code>meta</code> node level:

<pre>
...
"rateLimit": {
     "limit": 1200,
     "remaining": 1191,
     "reset": "2014-06-02T14:06:53Z"
}
...
</pre>

This way it would be more friendly to access rate limit values as client needed. I'm the author of [DigitalOcean Client in Java](http://github.com/jeevatkm/digitalocean-api-java).

**Comment by macb** [comment]
One issue around this is we use `204 No Content` for `DELETE` requests, however those requests still factor into your rate limit, which means the only way to convey that information at that point is in the headers.

It might be possible to duplicate the information into `meta` when the body is present, but then as a developer writing something against the api you'll have to write 2 implementations for parsing rate limit information or just rely on the always present header.

**Comment by jeevatkm** [comment]
Thanks @macb for your response.  Based on v2 public beta, I'm extracting rate limit values from headers and giving as unified access to values via response java object. When I look at it, it seems workaround at client library around values.

???: discussion is technical vs usage against APIs
Currently v2 APIs HTTP status code are-

<pre>
200=OK  // for GET
201=CREATED // for POST
202=ACCEPTED // for PUT
204=NO_CONTENT // for DELETE
apart from above  &gt; 400 && &lt; 510 - // for errors/exception/permissions etc..
</pre>

I was thought about that issue. We can make <code>202</code> status for <code>DELETE</code> too and making v2 API unified way of response value access :)

**Comment by jeevatkm** [comment]
Another candid reason for <code>DELETE</code> request to use <code>202=ACCEPTED</code> status code is:

Typically Delete request initiates a Action within DigitalOcean system, so it could possibly send <code>Action</code> information as a response instead of <code>204=NO_CONTENT</code>.

**Comment by KirkMunro** [comment]
I'm against pushing more header information into a response body.  In my opinion, some of the current information provided in a response body should be pushed into the header using standard, well-known header fields where it belongs (response count, page handling, etc.).  Please, don't push more header information into a message body.  That would not be following best practices for REST APIs.
