### ISSUE TITLE
Send Action information for DELETE API request

### ISSUE THREAD

**Issue by jeevatkm** [digitalocean/api-v2#84]
Could be useful to send <code>Action</code> details for DELETE request like other actions instead of <code>204=NO_CONTENT</code>. [Reference](https://github.com/digitaloceancloud/api-v2/issues/83#issuecomment-54223589) discussion at issue #83

**Comment by macb** [comment]
With API v2 we made the choice to move away from `DELETE` generating an action, which is why you action on the droplet resource directly and not `droplet/:id/action`. Is the response is `204`, then it is safe to proceed as if the droplet doesn't exist any longer.
