### ISSUE TITLE
General feedback on the v2 API

### ISSUE THREAD

**Issue by KirkMunro** [digitalocean/api-v2#85]
Having dug into the details of the v2 API a fair bit now, I wanted to share some general feedback about that API. I believe the design of the v2 API as a "fully RESTful" API (as quoted from the API documentation) is flawed.  Here are some reasons why:
- The API is not HATEOAS/Hypermedia-driven.  At all.  It is decribed as a "fully RESTful" API, yet it has only achieved REST level 2 (see: http://martinfowler.com/articles/richardsonMaturityModel.html).  As a result, it is much more difficult to use than it should be, pushing work that should be absorbed by the design on each developer wanting to consume the API, requiring URI construction and much more documentation than should be necessary, and resulting in very tight coupling between the client and the server.  What would otherwise be easy invocation of methods on your objects is completely lost because you don't have hyperlinks to the specific methods on your objects coming back as part of your object data.
- Just to reiterate this, because it's a big issue, the API in its current state requires very tight coupling between all clients and the server, with clients using client-defined, hard-coded links to perform API tasks that should be performed using links that are passed back from the server.  Clients should really only know one link: the entry-point into the API.  All other functionality should be invocable through hyperlinks that are sent back in message responses, starting with that entry-point.
- The API does not support agile development/evolution over time because it is tightly bound to a version number in the URI.  As a result, any breaking changes must be deferred until an entirely new version of the API is released, unless you plan on telling clients that consume your API when they need to update their code.
- The API pushes information that should be managed in headers inside of a response body. For example, the HEAD method is often used to identify the number of items that would come back frmo a web request.  Since the count of objects is pushed inside of the response body, clients cannot use the HEAD method to retrieve the count of objects in a collection.  To get the count, they must get the collection itself (or at least the first page of objects), which creates more network traffic and slower response times than should be necessary.  There are well-defined headers for count information, and they would allow for HEAD requests to be used appropriately.
- Pagination changes (page size, page number) requires URI manipulation, when that shouldn't be necessary.  There are well known headers to handle pagination properly in a RESTful API, allowing clients to get the page that they want the first time (and every time) without having to perform URI manipulation.
- It is much more difficult to create wrappers around the API than it should be, because much more knowledge is required from one call to the next.  Using a hypermedia-driven API would solve this, allowing for smart wrappers to be created much more easily.
- It would be much easier for clients if all objects had the same primary key property (id or slug, but not one or the other for different objects).
- Nested collection consumption requires URI construction.  Beating the same drum here, but this is a poor design.  For something like Domain Records, how about a Records URI that is attached to any domain objects that I get back, and if you want direct access, a DomainRecords URI attached to the top level URI that I initially connect to.  This would allow me to query the system to see what it can do without looking through so much documentation, and if the OPTIONS verb was supported I could discover that DomainRecords accepts a Domain name as a parameter.  This approach also enables clients to dynamically create forms based on information returned from the server.  It is a loosely coupled approach, and you can change your backend as necessary, with non-breaking changes simply being pushed in, and with breaking changes being handled with versioned resources.  It's self documenting, plus documentation that is required is baked in at the software level so that docs never become out of sync by being too far removed from what you have published in your API.

Here's another example where this is more painful to use than it should be.  If you wanted to take a snapshot of all of your droplets, using this API, this requires the following:
- knowing the endpoint to retrieve droplets
- knowing how to construct the URI for each individual droplet that comes back
- knowing how to identify the snapshot method on those droplets
- knowing what parameters are required for the snapshot method

Compare that to the HATEOAS approach, where I could connect to a single, root endpoint (the entry-point for the API), discover that there is a droplets hyperlink, pull down the droplets that are available through that link, and in those responses discover the snapshot method that is invocable via a dynamic URI (one which could be anything, and I shouldn't have to care about its format), as well as parameters used on that method by using the OPTIONS verb, so that I could more easily invoke the snapshot method, all without having to go looking elsewhere for docs and without having to construct any URIs myself.  The margin for error is reduced/eliminated because I am simply following links provided by the server, and if versioning is pushed into the media types (where it should be), then I can work with the version of the objects that I am familiar with while being able to evolve to newer versions that incur breaking changes when I am ready to do so, on a resource by resource basis (rather than having to switch to a completely new version of the API all at once).

I think that about sums up my issues with the API so far.  I hope this is helpful in driving this API towards a better design, if not now, then in v3 (which should be the last version number that is updated in the URI itself).  Thanks for listening.

**Comment by macb** [comment]
Hey @KirkMunro, thanks for the feedback. I think you might also be interested in #17 where someone else voiced concern at our use of "fully RESTful". As such, I removed that from our documentation.

**Comment by KirkMunro** [comment]
Hi @macb, thanks for correcting the documentation.  It was grossly overstating what the API was designed to be today, and I think the removal of that phrase will help others.  I read entry #17 over, and your positioning on HATEOAS right now is clear, which is unfortunate.  I'll keep hoping for a Hypermedia-driven REST API whenever you get around to your next version beyond this one.

**Comment by KirkMunro** [comment]
Just to add some additional justification for taking the HATEOAS approach for the DO API: when you invoke an action against a resource (renaming a droplet, for example), you get back a representation of  an object that describes the current state of that action.  This action state shows that the action is in progress.  This means client systems have to refresh (re-fetch) that action data if they want to see if the action has completed, which requires knowing how to construct the URI to retrieve a specific action.  That is trivial enough (although it incurs tight coupling as mentioned above), but then once the action has completed if a client system wants to retrieve the updated state of the resource upon which the action was performed, the client must have some way to retrieve that resource again, which requires knowing what base URI to use and how to retrieve a specific resource from that URI.  That means I have to keep track of which actions are associated with which objects on my side, or alternatively have some mapping logic to convert from the resource_type and resource_id properties of an action into the URI.  This is feasible for top-level resources, but if you ever provide actions on nested resources (e.g. something like Domain Records which require knowledge of multiple IDs to access them), it would become even more complicated.  All of that URI construction/mapping logic development and testing is a complete waste of time and energy that client developers and testers should be spending other work.

In a HATEOAS design, the action would have a hyperlink to itself (using the well-known "self" hyperlink name) as well as a link to the associated resource, allowing clients to refresh by simply invoking GET requests on hyperlinks that are managed by the server itself.  Wouldn't you prefer customers and partners integrating with your service to be able to spend their time and effort on more important work than creating and testing URI construction logic?

**Comment by brookemckim** [comment]
Kirk,

Thanks for some additional context. Our API v2 approach is well defined at this point, however we will keep all of this in mind for V3 as well as watching how our users interact with our API to provide enhancements.
