### ISSUE TITLE
Add possibility to reset Developer Applications' Client Secret without loosing Client ID 

### ISSUE THREAD

**Issue by dkapanidis** [digitalocean/api-v2#86]
Use Case:
A developer collects authorization from users, and then his client secret is exposed. Currently there is no alternative than re-registering the developer Application and loosing all authorizations done until the moment.

As in Personal Access Token there is a regenerate Token, it would be useful also for Developer Applications to regenerate the Client Secret while keeping the Client ID.

**Comment by bobbytables** [comment]
Thank you for providing a use case,

However Id like to provide the argument of: If you're already changing one,
why not change both? We can regenerate both and still retain user
authorizations.

On Tuesday, September 9, 2014, spiddy notifications@github.com wrote:

> Use Case:
> A developer collects authorization from users, and then his client secret
> is exposed. Currently there is no alternative than re-registering the
> developer Application and loosing all authorizations done until the moment.
> 
> As in Personal Access Token there is a regenerate Token, it would be
> useful also for Developer Applications to regenerate the Client Secret
> while keeping the Client ID.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/digitalocean/api-v2/issues/86.

## 
- Robert Ross

**Comment by dkapanidis** [comment]
That was quick,

I don't see a reason to change the Client ID (it is not a secret right?). Changing it implies it's a new Application.

Other than that, if necessary, I don't see a reason against changing it.
