### ISSUE TITLE
Add domain_name to domain_record resources

### ISSUE THREAD

**Issue by KirkMunro** [digitalocean/api-v2#89]
Since both the domain name and the record ID are required to remove or rename a DNS record, it would be better if domain_record resources included a domain_name parameter.  That way, all required information would be contained within one resource, making it easier for client systems and automation languages to take action on a single resource.

**Comment by brookemckim** [comment]
Kirk, thanks for the suggestion. We are currently working on wrapping up the API and will take this into consideration.

**Comment by phillbaker** [comment]
@KirkMunro as you point out, since the domain name and record id are already required, the client would already have access to that information. We won't be adding this to the record response at this time.
