### ISSUE TITLE
Would be great to get created_at of images and backups

### ISSUE THREAD

**Issue by bob-rove** [digitalocean/api-v2#9]
Hi!

Great to see the new version of API :+1: 

I think it would be very nice to get created_at for images and backups.

**Comment by brookemckim** [comment]
Yep, we can do this.

**Comment by macb** [comment]
hey @bob-rove, we added `created_at` for all instances of images. Thanks again for the feedback!

**Comment by bob-rove** [comment]
Awesome! :+1:
