### ISSUE TITLE
Shutdown does not work for my droplet via curl command in API v2

### ISSUE THREAD

**Issue by d19dotca** [digitalocean/api-v2#91]
I created a ticket with DO but when I pressed for a solution they directed me here.

I am having issues with running the Shutdown command. It works just fine and shows up in my event history of the droplet, yet it doesn't actually shutdown at all. Execution time is only 1 or 2 seconds at most and the droplet never does shutdown at all. Power_off works fine, but not shutdown. Shutdown works fine if I run that command from within the droplet itself, so the server is capable of being shutdown gracefully, but yet this command does not work. 

The call I made is below along with the output.

> DEED-Notebook:~ dustindauncey$ curl -X POST "https://api.digitalocean.com/v2/droplets/{dropletID}/actions" -d '{"type":"shutdown"}' -H "Authorization: Bearer {tokenString}" -H "Content-Type: application/json" 
> { 
> "action":{ 
> "id":{idNumber}, 
> "status":"in-progress", 
> "type":"shutdown", 
> "started_at":"2014-09-23T04:47:13Z", 
> "completed_at":null, 
> "resource_id":{dropletID}, 
> "resource_type":"droplet", 
> "region":"sfo1" 
> } 
> }

Any ideas? Any help would be greatly appreciated.

**Comment by macb** [comment]
Hmm, I didn't see the ticket but I'm not sure this is an issue with the API. It appears the action was successfully created and sounds like its processing as expected, but the shutdown itself is failing. 

`shutdown` is best effort and relies entirely on the machine itself responding and shutting itself down. A successful `power_off` is guaranteed to result in the droplet being turned off, but it could also result in corrupted data as it's essentially pulling the plug.

If you'd like to provide me with an action id of a `shutdown` I could take a look to make sure it processed as expected. Feel free to send it to mac@digitalocean.com.

similar to https://github.com/digitalocean/api-v2/issues/79
