### ISSUE TITLE
Can't create droplet with ssh keys assigned using requests python module. 

### ISSUE THREAD

**Issue by fizban79** [digitalocean/api-v2#92]
I'm trying to create droplet using Python "requests" module. When creating simple droplet with only required parameters (or all excluding SSH keys), everything works fine. When trying to create droplet with embedded SSH key - getting an error: "You specified invalid ssh key ids for Droplet creation.". I've tried to pass int, string, list, set - nothing works. 

Here is an example script reproducing this error: 

``` python
#!/usr/bin/python

import requests

api_key = "<MY_API_KEY>" 
url = 'https://api.digitalocean.com/v2/droplets' 
headers = { 'Authorization': "Bearer %s" % api_key } 
name = 'test' 
size_id = '512mb' 
image_id = 'ubuntu-14-04-x64' 
region_id = 'ams2' 
ssh_key_ids = [122800]

params = { 
    'name': name, 
    'size': size_id, 
    'image': image_id, 
    'region': region_id, 
    'virtio': False, 
    'private_networking': False, 
    'backups_enabled': False, 
} 
if ssh_key_ids: 
    params['ssh_keys'] = ssh_key_ids

resp = requests.post(url, params=params, headers=headers, timeout=60) 
print resp.json()
```

Request as JSON:  

``` json
{
    'virtio': False,
    'ssh_keys': [122800],
    'name': 'test11',
    'private_networking': False,
    'image': 'ubuntu-14-04-x64',
    'backups_enabled': False,
    'region': 'ams2',
    'size': '512mb'
} 
```

The same request, sent by curl utility as shown in examples, works fine. But only if its formatted exactly as shown - with double quotes everywhere: 

``` bash
curl -X POST "https://api.digitalocean.com/v2/droplets" \
    -d'{"name":"test","region":"ams2","size":"512mb","image":"lamp","ssh_keys":[122800]}' \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json"
```

Else i'm getting error about wrong JSON. 

I'm trying to adapt 'dopy' module to API v.2 now: https://github.com/fizban79/dopy
Everything else seems to be working excluding this.

**Comment by macb** [comment]
```
{
    'virtio': False,
    'ssh_keys': [122800],
    'name': 'test11',
    'private_networking': False,
    'image': 'ubuntu-14-04-x64',
    'backups_enabled': False,
    'region': 'ams2',
    'size': '512mb'
} 
```

That is not valid JSON. Strings should be wrapped in `"` not `'`.

I think you need an additional step, something like:

```
import requests
import json

.....

json_params = json.dumps(params)
resp = requests.post(url, params=json_params, headers=headers, timeout=60) 
```

**Comment by fizban79** [comment]
HI! 

Thank you for your suggestion! 
I was wrong - this is not JSON but Python dictionary dump. 
I don't know the internals of requests module, I suppose it converts variable to proper JSON because  without ssh_keys everything works fine.

I've tried to pass JSON there as you said. Other error appeared: 

$ ./test_do.py 
{u'message': u'You specified an invalid image for Droplet creation.', u'id': u'unprocessable_entity'}

May be there's a way to turn on some sort of debug output? I would like to see request exactly as it coming to API. May be there's a bug in requests module.

**Comment by brookemckim** [comment]
That error usually indicates the correct Content-Type header is not being set. 

`Content-Type: application/json` is required.

**Comment by fizban79** [comment]
Hello! 

Thank you very much! 
Everything works fine if 'Content-Type' header set and params are passed in JSON as data. Also, it works only if numeric parameters (such as image id or ssh key ids) are passed as strings (quoted). 

Here's working sample script if anyone needs it: 

``` python
#!/usr/bin/python

import requests
import json

api_key = "<MY_API_KEY>"
url = 'https://api.digitalocean.com/v2/droplets'
headers = {
        'Authorization': "Bearer %s" % api_key,
        'Content-Type': 'application/json', 
}
name = 'test'
size_id = '512mb'
image_id = '6372581'
region_id = 'ams2'
ssh_key_ids = ['122800']
params = {
        'name': name,
        'size': size_id,
        'image': image_id,
        'region': region_id,
        'virtio': False,
        'private_networking': False,
        'backups_enabled': False,
}
if ssh_key_ids:
        params['ssh_keys'] = ssh_key_ids

resp = requests.post(url, data=json.dumps(params), headers=headers, timeout=60)
from pprint import pprint
pprint(resp.json())
```

**Comment by brookemckim** [comment]
Glad to hear you got it work!
