### ISSUE TITLE
Clarification of the implication between "meta" and "links", and pagination in general

### ISSUE THREAD

**Issue by reynir** [digitalocean/api-v2#93]
From the _Meta_ section of the [documentation](https://developers.digitalocean.com/#meta):

> The meta object contains a total key that is set to the total number of objects returned by the request. This has implications on the links object and pagination.

What exactly does this mean? At first I understood it as the presence of `meta` implies the presence of `links`, but that does not seem to be the case. For example, if you request all `/actions` then `meta` will be present while `links` will not.

The reason I ask this is because I try to write static type definitions w/ JSON (de-)serializers (using [atdgen](http://mjambon.com/atdgen)), and I need to know the shapes of the results.

Another question: Should pagination always be handled? Or should I always expect the API to _maybe_ return a paginated result? The doc seems rather vague on when pagination can occur. It does always occur when opted for, or when using `/actions`, though.

Last question: Are there any consistency guarantees with pagination? I imagine there could be potential problems if you have a program that traverses `/actions`, and someone does something such that a new action is added. Then the program is (potentially) processing the same action more than once. I am considering giving a (lazy) stream "view" to paginated results, and it bothers me that this could possibly lead to an inconsistent result/"view".

I guess the answer to the last question is 'no'. Will there be any guarantees in the future? Some kind of sessions, maybe?

**Comment by macb** [comment]
I'll try to clear a few things up. From https://developers.digitalocean.com/#links: 

> By default, 25 objects are returned per page. If the response contains 25 objects or fewer, no links object will be returned.

This means if a resource would return a collection with less than 25 objects, we won't return pagination information, so no `links` object (unless of course you submit a `per_page` value thats less than the default).

The `meta` object is always present for collections and contains a `total` field. That `total` will reflect the total number of objects contained regardless of whether or not the result is paginated. For single resources, such as a droplet show (`/v2/droplets/$DROPLET_ID`), there is currently no `meta` information to return so no `meta` object is present. This may change in the future as we discover `meta` information customers find useful. The purpose of the `meta` object is to allow us some flexibility around our responses.

There isn't any guarantee and a plan for one hasn't been discussed. The sort of behavior you hinted at seems like it would be better served with a webhook type interface, which we have discussed but there is currently no date associated with it.

**Comment by reynir** [comment]
Thank you for your quick reply!

Just to make it clear: Can I assume the result will not be paginated unless asked for (using `?per_page`) or the documentation says so explicitly (e.g. `/actions`)?

**Comment by macb** [comment]
It would be safest to assume all collections are paginated, however if the total number of objects returned is less than the `per_page` (either the default of 25 or whatever the user specified value happens to be), no pagination information will be returned.
