### ISSUE TITLE
API keys

### ISSUE THREAD

**Issue by benjiqq** [digitalocean/api-v2#95]
Hello,

is the personal token a replacement for the API-key? Was not quite clear for me, from the documentation.

**Comment by andrewsomething** [comment]
Hi,

In APIv2 tokens have replaced the key/id pair. You can generate a Personal Access Token from the [control panel](https://cloud.digitalocean.com/settings/applications) and use it much like you did with the key/id pair:

```
curl -X GET "https://api.digitalocean.com/v2/droplets" \
    -H "Authorization: Bearer $TOKEN"
```

For scripting, this is probably what you want.

Applications can also use OAuth to have users authorize with their DigitalOcean account, for more information check out the OAuth docs and tutorial:

https://developers.digitalocean.com/oauth/
https://www.digitalocean.com/community/tutorials/how-to-use-oauth-authentication-with-digitalocean-as-a-user-or-developer
