### ISSUE TITLE
Update User Data

### ISSUE THREAD

**Issue by rampantmonkey** [digitalocean/api-v2#96]
I would like an option to update the user data for a droplet. This often comes up when experimenting with CoreOS and the need for new etcd discovery tokens as well as adding new systemd units.

**Comment by brookemckim** [comment]
After you update the user-data how do you let the Droplet know it should pick up this change? Are you doing a rebuild in this case?

I am going to close this issue as it is more of a product request than an API issue, but I would love to hear your exact use case.

**Comment by TrurlMcByte** [comment]
Looks like CoreOS use this data every reboot during 
`ExecStart=/usr/bin/coreos-cloudinit --oem=digitalocean`
So in this case possibility to update `user-data` very useful to preserve currently used IP address.
