### ISSUE TITLE
Make certain items public (no token required)

### ISSUE THREAD

**Issue by rogierslag** [digitalocean/api-v2#99]
For certain endpoints it makes no sense that authentication is required. An example is the command to list all images/slugs.

> However, this listing from the API is also protected by the API token. Since the information is already public, it makes not a lot of sense to protect the information. Better behaviour could possibly be to list the public information when an token is ommitted, and when one is sent along to show more customer specific information.

This would allow applications to list information when before people have to enter their complete tokens to the application.

**Comment by wwkeyboard** [comment]
I'll add this to our backlog for further discussion, but allowing non-authorized access to our API is a big change. Thank you for your feedback and for including a use case for this type of access. It will help when we further discuss this issue.
